"""
Agricultural Suitability Analysis Generator
Creates a sophisticated notebook for multi-criteria crop suitability mapping using MCDA
"""

import json

def create_notebook(cells):
    """Helper to create notebook structure."""
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.8.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }

def generate_agricultural_suitability_notebook():
    """Generate comprehensive agricultural suitability analysis notebook."""
    
    cells = [
        {"cell_type": "markdown", "metadata": {}, "source": [
            "# Agricultural Suitability Analysis - Multi-Criteria Decision Analysis\n\n",
            "## 🌾 Business Context\n",
            "Identify optimal locations for crop cultivation using weighted overlay analysis (MCDA) based on soil, climate, and topographic factors.\n\n",
            "**Key Objectives**:\n",
            "- Evaluate suitability for wheat, maize, and coffee cultivation\n",
            "- Apply fuzzy membership functions for continuous suitability scoring\n",
            "- Perform constraint mapping (exclude unsuitable areas)\n",
            "- Conduct sensitivity analysis on factor weights\n",
            "- Generate actionable land use recommendations\n\n",
            "**Study Area**: Ethiopian Highlands (agricultural region)\n\n",
            "**Applications**: Agricultural planning, food security, land use optimization"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Import Libraries\n",
            "import ee\n",
            "import geemap\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "from scipy import stats\n",
            "import os\n",
            "\n",
            "try:\n",
            "    ee.Initialize()\n",
            "except:\n",
            "    ee.Authenticate()\n",
            "    ee.Initialize()\n",
            "\n",
            "# Create outputs directory\n",
            "if not os.path.exists('outputs'):\n",
            "    os.makedirs('outputs')\n",
            "\n",
            "plt.style.use('seaborn-v0_8-darkgrid')\n",
            "sns.set_palette('Set2')\n",
            "print('✓ Libraries loaded successfully')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Define Study Area - Ethiopian Highlands\n",
            "# Coordinates for agricultural region in Ethiopia\n",
            "ethiopia_region = ee.Geometry.Rectangle([37.5, 8.5, 38.5, 9.5])\n",
            "\n",
            "# Time period for climate data\n",
            "start_date = '2020-01-01'\n",
            "end_date = '2023-12-31'\n",
            "\n",
            "print(f'Study Area: {ethiopia_region.area().divide(1e6).getInfo():.2f} km²')\n",
            "print(f'Analysis Period: {start_date} to {end_date}')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Load Datasets\n",
            "print('Loading datasets...')\n",
            "\n",
            "# 1. Topography - SRTM Elevation\n",
            "srtm = ee.Image('USGS/SRTMGL1_003').clip(ethiopia_region)\n",
            "elevation = srtm.select('elevation')\n",
            "slope = ee.Terrain.slope(elevation)\n",
            "aspect = ee.Terrain.aspect(elevation)\n",
            "\n",
            "# 2. Climate - Temperature and Precipitation\n",
            "# MODIS Land Surface Temperature\n",
            "modis_lst = ee.ImageCollection('MODIS/061/MOD11A2') \\\n",
            "    .filterDate(start_date, end_date) \\\n",
            "    .filterBounds(ethiopia_region) \\\n",
            "    .select('LST_Day_1km')\n",
            "\n",
            "# Convert to Celsius and get mean\n",
            "mean_temp = modis_lst.mean().multiply(0.02).subtract(273.15).rename('Temperature')\n",
            "\n",
            "# CHIRPS Precipitation\n",
            "chirps = ee.ImageCollection('UCSB-CHG/CHIRPS/DAILY') \\\n",
            "    .filterDate(start_date, end_date) \\\n",
            "    .filterBounds(ethiopia_region)\n",
            "\n",
            "# Annual precipitation (mm/year)\n",
            "annual_precip = chirps.sum().rename('Precipitation')\n",
            "\n",
            "# 3. Soil Properties - OpenLandMap\n",
            "# Soil pH\n",
            "soil_ph = ee.Image('OpenLandMap/SOL/SOL_PH-H2O_USDA-4C1A2A_M/v02') \\\n",
            "    .select('b0').multiply(0.1).clip(ethiopia_region).rename('SoilpH')\n",
            "\n",
            "# Soil Organic Carbon\n",
            "soil_oc = ee.Image('OpenLandMap/SOL/SOL_ORGANIC-CARBON_USDA-6A1C_M/v02') \\\n",
            "    .select('b0').multiply(0.002).clip(ethiopia_region).rename('SoilOC')\n",
            "\n",
            "# 4. Land Cover - ESA WorldCover (for constraints)\n",
            "landcover = ee.ImageCollection('ESA/WorldCover/v100').first().clip(ethiopia_region)\n",
            "\n",
            "print('✓ All datasets loaded')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Fuzzy Membership Functions\n",
            "# Convert raw values to 0-1 suitability scores\n",
            "\n",
            "def fuzzy_linear(image, min_val, max_val):\n",
            "    \"\"\"Linear membership: 0 at min_val, 1 at max_val.\"\"\"\n",
            "    return image.subtract(min_val).divide(max_val - min_val).clamp(0, 1)\n",
            "\n",
            "def fuzzy_gaussian(image, midpoint, spread):\n",
            "    \"\"\"Gaussian membership: peaks at midpoint, falls off with spread.\"\"\"\n",
            "    return image.subtract(midpoint).pow(2).divide(-2 * spread * spread).exp()\n",
            "\n",
            "def fuzzy_trapezoidal(image, a, b, c, d):\n",
            "    \"\"\"Trapezoidal: ramps up from a to b, flat from b to c, ramps down from c to d.\"\"\"\n",
            "    ramp_up = image.subtract(a).divide(b - a).clamp(0, 1)\n",
            "    ramp_down = image.subtract(d).divide(c - d).clamp(0, 1)\n",
            "    return ramp_up.min(ramp_down)\n",
            "\n",
            "print('✓ Fuzzy membership functions defined')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# WHEAT Suitability Analysis\n",
            "print('\\n=== WHEAT Suitability ===')\n",
            "\n",
            "# Optimal ranges for wheat:\n",
            "# Elevation: 1800-2800m, Temp: 15-25°C, Precip: 350-800mm, pH: 6.0-7.5, Slope: <15°\n",
            "\n",
            "wheat_elevation = fuzzy_trapezoidal(elevation, 1500, 1800, 2800, 3200)\n",
            "wheat_temp = fuzzy_trapezoidal(mean_temp, 12, 15, 25, 28)\n",
            "wheat_precip = fuzzy_trapezoidal(annual_precip, 300, 350, 800, 1000)\n",
            "wheat_ph = fuzzy_trapezoidal(soil_ph, 5.5, 6.0, 7.5, 8.0)\n",
            "wheat_slope = fuzzy_linear(slope.multiply(-1).add(15), -5, 15)  # Inverse: lower slope = better\n",
            "\n",
            "# MCDA Weights (must sum to 1.0)\n",
            "weights_wheat = {\n",
            "    'elevation': 0.20,\n",
            "    'temperature': 0.25,\n",
            "    'precipitation': 0.30,\n",
            "    'soil_ph': 0.15,\n",
            "    'slope': 0.10\n",
            "}\n",
            "\n",
            "# Weighted overlay\n",
            "wheat_suitability = wheat_elevation.multiply(weights_wheat['elevation']) \\\n",
            "    .add(wheat_temp.multiply(weights_wheat['temperature'])) \\\n",
            "    .add(wheat_precip.multiply(weights_wheat['precipitation'])) \\\n",
            "    .add(wheat_ph.multiply(weights_wheat['soil_ph'])) \\\n",
            "    .add(wheat_slope.multiply(weights_wheat['slope'])) \\\n",
            "    .rename('Wheat_Suitability')\n",
            "\n",
            "# Calculate statistics\n",
            "wheat_stats = wheat_suitability.reduceRegion(\n",
            "    reducer=ee.Reducer.mean().combine(ee.Reducer.stdDev(), '', True),\n",
            "    geometry=ethiopia_region,\n",
            "    scale=1000,\n",
            "    maxPixels=1e9\n",
            ").getInfo()\n",
            "\n",
            "print(f'Mean Suitability: {wheat_stats[\"Wheat_Suitability_mean\"]:.3f}')\n",
            "print(f'Std Dev: {wheat_stats[\"Wheat_Suitability_stdDev\"]:.3f}')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# MAIZE Suitability Analysis\n",
            "print('\\n=== MAIZE Suitability ===')\n",
            "\n",
            "# Optimal ranges for maize:\n",
            "# Elevation: 0-2000m, Temp: 18-30°C, Precip: 500-1200mm, pH: 5.5-7.0, Slope: <20°\n",
            "\n",
            "maize_elevation = fuzzy_linear(elevation.multiply(-1).add(2000), -500, 2000)\n",
            "maize_temp = fuzzy_trapezoidal(mean_temp, 15, 18, 30, 33)\n",
            "maize_precip = fuzzy_trapezoidal(annual_precip, 400, 500, 1200, 1400)\n",
            "maize_ph = fuzzy_trapezoidal(soil_ph, 5.0, 5.5, 7.0, 7.5)\n",
            "maize_slope = fuzzy_linear(slope.multiply(-1).add(20), -5, 20)\n",
            "\n",
            "weights_maize = {\n",
            "    'elevation': 0.15,\n",
            "    'temperature': 0.30,\n",
            "    'precipitation': 0.35,\n",
            "    'soil_ph': 0.10,\n",
            "    'slope': 0.10\n",
            "}\n",
            "\n",
            "maize_suitability = maize_elevation.multiply(weights_maize['elevation']) \\\n",
            "    .add(maize_temp.multiply(weights_maize['temperature'])) \\\n",
            "    .add(maize_precip.multiply(weights_maize['precipitation'])) \\\n",
            "    .add(maize_ph.multiply(weights_maize['soil_ph'])) \\\n",
            "    .add(maize_slope.multiply(weights_maize['slope'])) \\\n",
            "    .rename('Maize_Suitability')\n",
            "\n",
            "maize_stats = maize_suitability.reduceRegion(\n",
            "    reducer=ee.Reducer.mean().combine(ee.Reducer.stdDev(), '', True),\n",
            "    geometry=ethiopia_region,\n",
            "    scale=1000,\n",
            "    maxPixels=1e9\n",
            ").getInfo()\n",
            "\n",
            "print(f'Mean Suitability: {maize_stats[\"Maize_Suitability_mean\"]:.3f}')\n",
            "print(f'Std Dev: {maize_stats[\"Maize_Suitability_stdDev\"]:.3f}')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# COFFEE Suitability Analysis\n",
            "print('\\n=== COFFEE Suitability ===')\n",
            "\n",
            "# Optimal ranges for coffee (Arabica):\n",
            "# Elevation: 1200-2200m, Temp: 15-24°C, Precip: 1200-2000mm, pH: 6.0-6.5, Slope: 5-30° (well-drained)\n",
            "\n",
            "coffee_elevation = fuzzy_trapezoidal(elevation, 1000, 1200, 2200, 2500)\n",
            "coffee_temp = fuzzy_trapezoidal(mean_temp, 13, 15, 24, 27)\n",
            "coffee_precip = fuzzy_trapezoidal(annual_precip, 1000, 1200, 2000, 2300)\n",
            "coffee_ph = fuzzy_gaussian(soil_ph, 6.25, 0.5)  # Peak at 6.25\n",
            "coffee_slope = fuzzy_trapezoidal(slope, 3, 5, 30, 35)  # Prefers some slope for drainage\n",
            "\n",
            "weights_coffee = {\n",
            "    'elevation': 0.25,\n",
            "    'temperature': 0.30,\n",
            "    'precipitation': 0.25,\n",
            "    'soil_ph': 0.10,\n",
            "    'slope': 0.10\n",
            "}\n",
            "\n",
            "coffee_suitability = coffee_elevation.multiply(weights_coffee['elevation']) \\\n",
            "    .add(coffee_temp.multiply(weights_coffee['temperature'])) \\\n",
            "    .add(coffee_precip.multiply(weights_coffee['precipitation'])) \\\n",
            "    .add(coffee_ph.multiply(weights_coffee['soil_ph'])) \\\n",
            "    .add(coffee_slope.multiply(weights_coffee['slope'])) \\\n",
            "    .rename('Coffee_Suitability')\n",
            "\n",
            "coffee_stats = coffee_suitability.reduceRegion(\n",
            "    reducer=ee.Reducer.mean().combine(ee.Reducer.stdDev(), '', True),\n",
            "    geometry=ethiopia_region,\n",
            "    scale=1000,\n",
            "    maxPixels=1e9\n",
            ").getInfo()\n",
            "\n",
            "print(f'Mean Suitability: {coffee_stats[\"Coffee_Suitability_mean\"]:.3f}')\n",
            "print(f'Std Dev: {coffee_stats[\"Coffee_Suitability_stdDev\"]:.3f}')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Constraint Mapping - Exclude unsuitable areas\n",
            "# Exclude: Urban areas (50), Water bodies (80), Bare/sparse vegetation (60)\n",
            "\n",
            "lc_band = landcover.select('Map')\n",
            "urban = lc_band.eq(50)\n",
            "water = lc_band.eq(80)\n",
            "bare = lc_band.eq(60)\n",
            "\n",
            "# Create constraint mask (0 = exclude, 1 = include)\n",
            "constraint_mask = urban.Or(water).Or(bare).Not()\n",
            "\n",
            "# Apply constraints to all suitability maps\n",
            "wheat_final = wheat_suitability.updateMask(constraint_mask)\n",
            "maize_final = maize_suitability.updateMask(constraint_mask)\n",
            "coffee_final = coffee_suitability.updateMask(constraint_mask)\n",
            "\n",
            "# Calculate excluded area\n",
            "excluded_area_sqkm = urban.Or(water).Or(bare).multiply(ee.Image.pixelArea()).reduceRegion(\n",
            "    reducer=ee.Reducer.sum(),\n",
            "    geometry=ethiopia_region,\n",
            "    scale=100,\n",
            "    maxPixels=1e9\n",
            ").get('Map').getInfo() / 1e6\n",
            "\n",
            "print(f'\\nExcluded area (urban, water, bare): {excluded_area_sqkm:.2f} km²')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Classification into Suitability Classes\n",
            "def classify_suitability(image):\n",
            "    \"\"\"Classify continuous suitability into discrete classes.\"\"\"\n",
            "    return image.expression(\n",
            "        '(s >= 0.75) ? 4' +  # Highly Suitable\n",
            "        ': (s >= 0.50) ? 3' +  # Suitable\n",
            "        ': (s >= 0.25) ? 2' +  # Moderately Suitable\n",
            "        ': (s >= 0.10) ? 1' +  # Marginally Suitable\n",
            "        ': 0',  # Not Suitable\n",
            "        {'s': image}\n",
            "    )\n",
            "\n",
            "wheat_classes = classify_suitability(wheat_final)\n",
            "maize_classes = classify_suitability(maize_final)\n",
            "coffee_classes = classify_suitability(coffee_final)\n",
            "\n",
            "# Calculate area per class\n",
            "def calculate_class_areas(image_classes, crop_name):\n",
            "    class_names = ['Not Suitable', 'Marginally', 'Moderately', 'Suitable', 'Highly Suitable']\n",
            "    areas = {}\n",
            "    \n",
            "    for i in range(5):\n",
            "        area = image_classes.eq(i).multiply(ee.Image.pixelArea()).reduceRegion(\n",
            "            reducer=ee.Reducer.sum(),\n",
            "            geometry=ethiopia_region,\n",
            "            scale=1000,\n",
            "            maxPixels=1e9\n",
            "        ).get('constant').getInfo() / 1e6\n",
            "        areas[class_names[i]] = area\n",
            "    \n",
            "    return pd.DataFrame([areas], index=[crop_name])\n",
            "\n",
            "wheat_areas = calculate_class_areas(wheat_classes, 'Wheat')\n",
            "maize_areas = calculate_class_areas(maize_classes, 'Maize')\n",
            "coffee_areas = calculate_class_areas(coffee_classes, 'Coffee')\n",
            "\n",
            "area_df = pd.concat([wheat_areas, maize_areas, coffee_areas])\n",
            "print('\\nSuitability Class Areas (km²):')\n",
            "display(area_df.round(2))"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Visualizations - Part 1: Suitability Maps\n",
            "fig = plt.figure(figsize=(20, 14))\n",
            "gs = fig.add_gridspec(4, 3, hspace=0.35, wspace=0.3)\n",
            "\n",
            "# 1. Wheat Suitability Map\n",
            "m1 = geemap.Map()\n",
            "m1.centerObject(ethiopia_region, 9)\n",
            "suit_vis = {'min': 0, 'max': 1, 'palette': ['red', 'orange', 'yellow', 'lightgreen', 'darkgreen']}\n",
            "m1.addLayer(wheat_final, suit_vis, 'Wheat Suitability')\n",
            "\n",
            "# 2. Maize Suitability Map\n",
            "m2 = geemap.Map()\n",
            "m2.centerObject(ethiopia_region, 9)\n",
            "m2.addLayer(maize_final, suit_vis, 'Maize Suitability')\n",
            "\n",
            "# 3. Coffee Suitability Map\n",
            "m3 = geemap.Map()\n",
            "m3.centerObject(ethiopia_region, 9)\n",
            "m3.addLayer(coffee_final, suit_vis, 'Coffee Suitability')\n",
            "\n",
            "print('✓ Interactive maps created (display separately)')\n",
            "\n",
            "# 4. Stacked Bar Chart - Area by Suitability Class\n",
            "ax1 = fig.add_subplot(gs[0, :])\n",
            "area_df.T.plot(kind='bar', ax=ax1, color=['wheat', 'gold', 'brown'], edgecolor='black', width=0.8)\n",
            "ax1.set_xlabel('Suitability Class', fontweight='bold')\n",
            "ax1.set_ylabel('Area (km²)', fontweight='bold')\n",
            "ax1.set_title('Land Suitability by Crop and Class', fontsize=14, fontweight='bold')\n",
            "ax1.legend(title='Crop', loc='upper right')\n",
            "ax1.grid(axis='y', alpha=0.3)\n",
            "ax1.set_xticklabels(ax1.get_xticklabels(), rotation=45, ha='right')\n",
            "\n",
            "# 5. Radar Chart - MCDA Weights\n",
            "ax2 = fig.add_subplot(gs[1, 0], projection='polar')\n",
            "categories = list(weights_wheat.keys())\n",
            "N = len(categories)\n",
            "angles = np.linspace(0, 2 * np.pi, N, endpoint=False).tolist()\n",
            "angles += angles[:1]\n",
            "\n",
            "wheat_vals = list(weights_wheat.values()) + [list(weights_wheat.values())[0]]\n",
            "maize_vals = list(weights_maize.values()) + [list(weights_maize.values())[0]]\n",
            "coffee_vals = list(weights_coffee.values()) + [list(weights_coffee.values())[0]]\n",
            "\n",
            "ax2.plot(angles, wheat_vals, 'o-', linewidth=2, label='Wheat', color='wheat')\n",
            "ax2.fill(angles, wheat_vals, alpha=0.25, color='wheat')\n",
            "ax2.plot(angles, maize_vals, 'o-', linewidth=2, label='Maize', color='gold')\n",
            "ax2.fill(angles, maize_vals, alpha=0.25, color='gold')\n",
            "ax2.plot(angles, coffee_vals, 'o-', linewidth=2, label='Coffee', color='brown')\n",
            "ax2.fill(angles, coffee_vals, alpha=0.25, color='brown')\n",
            "\n",
            "ax2.set_xticks(angles[:-1])\n",
            "ax2.set_xticklabels(categories, size=9)\n",
            "ax2.set_ylim(0, 0.4)\n",
            "ax2.set_title('MCDA Factor Weights', fontweight='bold', pad=20)\n",
            "ax2.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1))\n",
            "ax2.grid(True)\n",
            "\n",
            "# 6. Correlation Heatmap - Input Factors\n",
            "ax3 = fig.add_subplot(gs[1, 1])\n",
            "# Sample data for correlation\n",
            "sample_points = ee.FeatureCollection.randomPoints(ethiopia_region, 200, seed=42)\n",
            "combined = ee.Image.cat([elevation, slope, mean_temp, annual_precip, soil_ph])\n",
            "sample_data = combined.sampleRegions(\n",
            "    collection=sample_points,\n",
            "    scale=1000\n",
            ").getInfo()['features']\n",
            "\n",
            "sample_df = pd.DataFrame([f['properties'] for f in sample_data])\n",
            "sample_df = sample_df.rename(columns={\n",
            "    'elevation': 'Elevation',\n",
            "    'slope': 'Slope',\n",
            "    'Temperature': 'Temp',\n",
            "    'Precipitation': 'Precip',\n",
            "    'SoilpH': 'pH'\n",
            "})\n",
            "\n",
            "corr_matrix = sample_df.corr()\n",
            "sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', center=0, ax=ax3, fmt='.2f', cbar_kws={'shrink': 0.8})\n",
            "ax3.set_title('Factor Correlation Matrix', fontweight='bold')\n",
            "\n",
            "# 7. Histogram - Suitability Score Distribution\n",
            "ax4 = fig.add_subplot(gs[1, 2])\n",
            "bins = np.linspace(0, 1, 20)\n",
            "ax4.hist([wheat_stats['Wheat_Suitability_mean']], bins=bins, alpha=0.6, label='Wheat', color='wheat', edgecolor='black')\n",
            "ax4.hist([maize_stats['Maize_Suitability_mean']], bins=bins, alpha=0.6, label='Maize', color='gold', edgecolor='black')\n",
            "ax4.hist([coffee_stats['Coffee_Suitability_mean']], bins=bins, alpha=0.6, label='Coffee', color='brown', edgecolor='black')\n",
            "ax4.set_xlabel('Suitability Score', fontweight='bold')\n",
            "ax4.set_ylabel('Frequency (Mean Values)', fontweight='bold')\n",
            "ax4.set_title('Suitability Score Distributions', fontweight='bold')\n",
            "ax4.legend()\n",
            "ax4.grid(axis='y', alpha=0.3)\n",
            "\n",
            "plt.suptitle('Agricultural Suitability Analysis - Ethiopian Highlands', fontsize=16, fontweight='bold', y=0.995)\n",
            "plt.savefig('outputs/suitability_analysis_dashboard.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()\n",
            "\n",
            "# Save maps\n",
            "m1.to_html('outputs/wheat_suitability_map.html')\n",
            "m2.to_html('outputs/maize_suitability_map.html')\n",
            "m3.to_html('outputs/coffee_suitability_map.html')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Visualizations - Part 2: Constraint Map & Pie Charts\n",
            "fig2 = plt.figure(figsize=(18, 10))\n",
            "gs2 = fig2.add_gridspec(2, 3, hspace=0.3, wspace=0.3)\n",
            "\n",
            "# 8. Constraint Map\n",
            "ax5 = fig2.add_subplot(gs2[0, :])\n",
            "constraint_stats = {\n",
            "    'Urban': urban.multiply(ee.Image.pixelArea()).reduceRegion(ee.Reducer.sum(), ethiopia_region, 1000, 1e9).get('Map').getInfo() / 1e6,\n",
            "    'Water': water.multiply(ee.Image.pixelArea()).reduceRegion(ee.Reducer.sum(), ethiopia_region, 1000, 1e9).get('Map').getInfo() / 1e6,\n",
            "    'Bare': bare.multiply(ee.Image.pixelArea()).reduceRegion(ee.Reducer.sum(), ethiopia_region, 1000, 1e9).get('Map').getInfo() / 1e6\n",
            "}\n",
            "ax5.barh(list(constraint_stats.keys()), list(constraint_stats.values()), color=['gray', 'blue', 'tan'], edgecolor='black')\n",
            "ax5.set_xlabel('Area (km²)', fontweight='bold')\n",
            "ax5.set_title('Excluded Areas (Constraints)', fontweight='bold', fontsize=12)\n",
            "ax5.grid(axis='x', alpha=0.3)\n",
            "\n",
            "# 9-11. Pie Charts for each crop\n",
            "for idx, (crop, crop_areas_df) in enumerate([(('Wheat', wheat_areas), ('Maize', maize_areas), ('Coffee', coffee_areas))[i] for i in range(3)]):\n",
            "    ax = fig2.add_subplot(gs2[1, idx])\n",
            "    areas = crop_areas_df.iloc[0].values\n",
            "    labels = crop_areas_df.columns\n",
            "    colors = ['darkred', 'orange', 'yellow', 'lightgreen', 'darkgreen']\n",
            "    \n",
            "    wedges, texts, autotexts = ax.pie(areas, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)\n",
            "    for autotext in autotexts:\n",
            "        autotext.set_color('white')\n",
            "        autotext.set_fontweight('bold')\n",
            "    ax.set_title(f'{crop[0]} Land Suitability Breakdown', fontweight='bold')\n",
            "\n",
            "plt.suptitle('Constraint Analysis & Suitability Breakdowns', fontsize=14, fontweight='bold', y=0.98)\n",
            "plt.savefig('outputs/constraint_analysis_dashboard.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Sensitivity Analysis - Impact of Weight Variations\n",
            "print('\\n=== Sensitivity Analysis ===')\n",
            "print('Testing impact of ±20% weight changes on wheat suitability\\n')\n",
            "\n",
            "# Vary precipitation weight (most important for wheat)\n",
            "sensitivity_results = []\n",
            "\n",
            "for weight_change in [-0.20, -0.10, 0, 0.10, 0.20]:\n",
            "    # Adjust weights proportionally\n",
            "    new_precip_weight = weights_wheat['precipitation'] * (1 + weight_change)\n",
            "    adjustment = (weights_wheat['precipitation'] - new_precip_weight) / 4  # Distribute to other factors\n",
            "    \n",
            "    new_weights = {\n",
            "        'elevation': weights_wheat['elevation'] + adjustment,\n",
            "        'temperature': weights_wheat['temperature'] + adjustment,\n",
            "        'precipitation': new_precip_weight,\n",
            "        'soil_ph': weights_wheat['soil_ph'] + adjustment,\n",
            "        'slope': weights_wheat['slope'] + adjustment\n",
            "    }\n",
            "    \n",
            "    # Recalculate suitability\n",
            "    new_suit = wheat_elevation.multiply(new_weights['elevation']) \\\n",
            "        .add(wheat_temp.multiply(new_weights['temperature'])) \\\n",
            "        .add(wheat_precip.multiply(new_weights['precipitation'])) \\\n",
            "        .add(wheat_ph.multiply(new_weights['soil_ph'])) \\\n",
            "        .add(wheat_slope.multiply(new_weights['slope']))\n",
            "    \n",
            "    mean_suit = new_suit.reduceRegion(\n",
            "        reducer=ee.Reducer.mean(),\n",
            "        geometry=ethiopia_region,\n",
            "        scale=1000,\n",
            "        maxPixels=1e9\n",
            "    ).get('elevation').getInfo()\n",
            "    \n",
            "    sensitivity_results.append({\n",
            "        'Weight Change (%)': weight_change * 100,\n",
            "        'Precip Weight': new_precip_weight,\n",
            "        'Mean Suitability': mean_suit\n",
            "    })\n",
            "\n",
            "sens_df = pd.DataFrame(sensitivity_results)\n",
            "print(sens_df.round(3))\n",
            "\n",
            "# Plot sensitivity\n",
            "plt.figure(figsize=(10, 6))\n",
            "plt.plot(sens_df['Weight Change (%)'], sens_df['Mean Suitability'], 'o-', linewidth=2, markersize=8, color='darkgreen')\n",
            "plt.axhline(wheat_stats['Wheat_Suitability_mean'], color='red', linestyle='--', label='Baseline')\n",
            "plt.xlabel('Precipitation Weight Change (%)', fontweight='bold')\n",
            "plt.ylabel('Mean Suitability Score', fontweight='bold')\n",
            "plt.title('Sensitivity Analysis: Impact of Weight Variations on Wheat Suitability', fontweight='bold')\n",
            "plt.grid(alpha=0.3)\n",
            "plt.legend()\n",
            "plt.savefig('outputs/sensitivity_analysis.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Best Crop Recommendation Map (Pixel-wise)\n",
            "# For each pixel, select the crop with highest suitability score\n",
            "\n",
            "# Stack all suitability maps\n",
            "all_crops = ee.Image.cat([wheat_final, maize_final, coffee_final])\n",
            "\n",
            "# Find the band (crop) with maximum value\n",
            "best_crop = all_crops.arrayArgmax().arrayGet([0])\n",
            "best_value = all_crops.reduce(ee.Reducer.max())\n",
            "\n",
            "# Only show where suitability is > 0.5\n",
            "best_crop_masked = best_crop.updateMask(best_value.gt(0.5))\n",
            "\n",
            "# Calculate area per recommended crop\n",
            "best_crop_areas = {}\n",
            "crop_names = ['Wheat', 'Maize', 'Coffee']\n",
            "for i, crop in enumerate(crop_names):\n",
            "    area = best_crop_masked.eq(i).multiply(ee.Image.pixelArea()).reduceRegion(\n",
            "        reducer=ee.Reducer.sum(),\n",
            "        geometry=ethiopia_region,\n",
            "        scale=1000,\n",
            "        maxPixels=1e9\n",
            "    ).get('Wheat_Suitability').getInfo() / 1e6\n",
            "    best_crop_areas[crop] = area\n",
            "\n",
            "print('\\n=== Optimal Crop Recommendation (Area km²) ===')\n",
            "for crop, area in best_crop_areas.items():\n",
            "    print(f'{crop}: {area:.2f} km²')\n",
            "\n",
            "# Visualization: Best Crop Map\n",
            "m_best = geemap.Map()\n",
            "m_best.centerObject(ethiopia_region, 9)\n",
            "best_crop_vis = {'min': 0, 'max': 2, 'palette': ['wheat', 'gold', 'brown']}\n",
            "m_best.addLayer(best_crop_masked, best_crop_vis, 'Best Crop Recommendation')\n",
            "m_best.add_legend(title='Recommended Crop', legend_dict={'Wheat': 'wheat', 'Maize': 'gold', 'Coffee': 'brown'})\n",
            "\n",
            "# Bar chart\n",
            "plt.figure(figsize=(10, 6))\n",
            "plt.bar(best_crop_areas.keys(), best_crop_areas.values(), color=['wheat', 'gold', 'brown'], edgecolor='black', width=0.6)\n",
            "plt.ylabel('Recommended Area (km²)', fontweight='bold', fontsize=12)\n",
            "plt.title('Optimal Crop Selection by Area', fontweight='bold', fontsize=14)\n",
            "plt.grid(axis='y', alpha=0.3)\n",
            "for i, (crop, area) in enumerate(best_crop_areas.items()):\n",
            "    plt.text(i, area + 5, f'{area:.1f}', ha='center', fontweight='bold')\n",
            "plt.savefig('outputs/best_crop_recommendation_chart.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()\n",
            "\n",
            "m_best.to_html('outputs/best_crop_recommendation_map.html')\n",
            "\n",
            "print('\\n✓ Best crop recommendation map created')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Display Interactive Maps\n",
            "print('\\n=== Interactive Maps ===')\n",
            "print('Map 1: Wheat Suitability')\n",
            "display(m1)\n",
            "\n",
            "print('\\nMap 2: Maize Suitability')\n",
            "display(m2)\n",
            "\n",
            "print('\\nMap 3: Coffee Suitability')\n",
            "display(m3)\n",
            "\n",
            "print('\\nMap 4: Best Crop Recommendation')\n",
            "display(m_best)"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Climate Change Impact Scenarios\n",
            "print('\\n=== Climate Change Impact Scenarios ===')\n",
            "\n",
            "# Simulate +2°C temperature increase and -10% precipitation\n",
            "temp_increase = 2.0\n",
            "precip_decrease = 0.90\n",
            "\n",
            "# Adjust climate inputs\n",
            "future_temp = mean_temp.add(temp_increase)\n",
            "future_precip = annual_precip.multiply(precip_decrease)\n",
            "\n",
            "# Recalculate Wheat Suitability (most sensitive)\n",
            "future_wheat_temp = fuzzy_trapezoidal(future_temp, 12, 15, 25, 28)\n",
            "future_wheat_precip = fuzzy_trapezoidal(future_precip, 300, 350, 800, 1000)\n",
            "\n",
            "future_wheat_suitability = wheat_elevation.multiply(weights_wheat['elevation']) \\\n",
            "    .add(future_wheat_temp.multiply(weights_wheat['temperature'])) \\\n",
            "    .add(future_wheat_precip.multiply(weights_wheat['precipitation'])) \\\n",
            "    .add(wheat_ph.multiply(weights_wheat['soil_ph'])) \\\n",
            "    .add(wheat_slope.multiply(weights_wheat['slope']))\n",
            "\n",
            "# Compare stats\n",
            "future_stats = future_wheat_suitability.reduceRegion(\n",
            "    reducer=ee.Reducer.mean(),\n",
            "    geometry=ethiopia_region,\n",
            "    scale=1000,\n",
            "    maxPixels=1e9\n",
            ").get('elevation').getInfo()\n",
            "\n",
            "change = ((future_stats - wheat_stats['Wheat_Suitability_mean']) / wheat_stats['Wheat_Suitability_mean']) * 100\n",
            "print(f'Current Mean Suitability: {wheat_stats[\"Wheat_Suitability_mean\"]:.3f}')\n",
            "print(f'Future Mean Suitability (+2°C, -10% Rain): {future_stats:.3f}')\n",
            "print(f'Projected Impact: {change:+.2f}%')"
        ]},

        {"cell_type": "code", "metadata": {}, "source": [
            "# Generate Dynamic Summary Report\n",
            "from IPython.display import Markdown, display\n",
            "\n",
            "summary_md = f\"\"\"\n",
            "## 🎯 Key Findings & Recommendations\n\n",
            "### Suitability Assessment Summary\n\n",
            "1. **Wheat**: Mean suitability of {wheat_stats['Wheat_Suitability_mean']:.3f} indicates {'high' if wheat_stats['Wheat_Suitability_mean'] > 0.6 else 'moderate'} potential. The region's elevation is well-suited.\n",
            "2. **Maize**: Mean suitability of {maize_stats['Maize_Suitability_mean']:.3f} suggests {'excellent' if maize_stats['Maize_Suitability_mean'] > 0.6 else 'good'} conditions.\n",
            "3. **Coffee**: Mean suitability of {coffee_stats['Coffee_Suitability_mean']:.3f} reflects premium growing conditions.\n\n",
            "### Climate Resilience\n",
            "- **Scenario (+2°C, -10% Rain)**: Wheat suitability projected to change by {change:+.2f}%. Adaptation strategies (drought-tolerant varieties) are critical.\n\n",
            "### Implementation Recommendations\n\n",
            "#### 1. Spatial Prioritization\n",
            "- **High Suitability Zones** (>0.75): Priority for commercial investment.\n",
            "- **Marginal Zones** (<0.50): Requires irrigation and soil amendments.\n\n",
            "#### 2. Crop Allocation Strategy\n",
            "Based on optimal crop recommendation:\n",
            "- **Wheat**: {best_crop_areas.get('Wheat', 0):.0f} km² (Highlands)\n",
            "- **Maize**: {best_crop_areas.get('Maize', 0):.0f} km² (Mid-lowlands)\n",
            "- **Coffee**: {best_crop_areas.get('Coffee', 0):.0f} km² (Slopes)\n\n",
            "### Next Steps\n",
            "1. Validate with ground yield data.\n",
            "2. Pilot precision agriculture in top 10% zones.\n",
            "3. Develop extension programs for climate adaptation.\n",
            "\"\"\"\n",
            "display(Markdown(summary_md))"
        ]}
    ]
    
    return json.dumps(create_notebook(cells), indent=1)

if __name__ == "__main__":
    print("Generating Agricultural Suitability Analysis notebook...")
    nb_json = generate_agricultural_suitability_notebook()
    print(f"✓ Generated notebook with {len(json.loads(nb_json)['cells'])} cells")
