"""
FINAL CUSTOM GENERATORS + COMPLETE PORTFOLIO GENERATION
Hybrid approach: 6 custom + 30 enhanced = 36 total notebooks
"""

import os
import json

BASE_DIR = os.path.join(os.path.dirname(__file__), "Projects")

def create_notebook(cells):
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py", "mimetype": "text/x-python",
                "name": "python", "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3", "version": "3.8.0"
            }
        },
        "nbformat": 4, "nbformat_minor": 4
    }

# ==============================================================================
# GENERATOR 5: CUSTOMER SEGMENTATION (RFM + CLV)
# ==============================================================================

def generate_customer_segmentation_notebook():
    """Customer segmentation with RFM analysis and CLV modeling."""
    
    cells = [
        {"cell_type": "markdown", "metadata": {}, "source": [
            "# Customer Segmentation - RFM Analysis & Lifetime Value\n\n",
            "## 📊 Business Context\n",
            "Segment customers using RFM (Recency, Frequency, Monetary) analysis and predict Customer Lifetime Value (CLV) for targeted marketing.\n\n",
            "**Objectives**:\n",
            "- Calculate RFM scores for each customer\n",
            "- Perform K-means & Hierarchical clustering\n",
            "- Predict Customer Lifetime Value (CLV)\n",
            "- Create actionable segment profiles\n",
            "- Estimate marketing ROI per segment\n\n",
            "**Business Impact**: Personalized campaigns, retention strategies, resource allocation"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "import pandas as pd\n",
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "from sklearn.preprocessing import StandardScaler\n",
            "from sklearn.cluster import KMeans, AgglomerativeClustering\n",
            "from sklearn.decomposition import PCA\n",
            "from sklearn.metrics import silhouette_score, davies_bouldin_score\n",
            "from scipy.cluster.hierarchy import dendrogram, linkage\n",
            "from datetime import datetime, timedelta\n",
            "import warnings\n",
            "warnings.filterwarnings('ignore')\n",
            "\n",
            "plt.style.use('seaborn-v0_8-whitegrid')\n",
            "print('✓ Libraries loaded')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Generate Synthetic Customer Data\n",
            "np.random.seed(42)\n",
            "n_customers = 2000\n",
            "\n",
            "# Simulate transaction history\n",
            "end_date = datetime(2024, 1, 1)\n",
            "customers = pd.DataFrame({\n",
            "    'customer_id': range(1, n_customers + 1),\n",
            "    'last_purchase_days': np.random.exponential(30, n_customers).astype(int),\n",
            "    'purchase_frequency': np.random.poisson(8, n_customers),\n",
            "    'total_spend': np.random.gamma(100, 50, n_customers),\n",
            "    'avg_order_value': np.random.normal(150, 60, n_customers),\n",
            "    'tenure_months': np.random.randint(1, 60, n_customers),\n",
            "    'customer_age': np.random.normal(40, 15, n_customers).astype(int).clip(18, 80)\n",
            "})\n",
            "\n",
            "# Ensure positive values\n",
            "customers['total_spend'] = customers['total_spend'].clip(lower=50)\n",
            "customers['avg_order_value'] = customers['avg_order_value'].clip(lower=20)\n",
            "\n",
            "print(f'Dataset: {customers.shape[0]:,} customers')\n",
            "display(customers.head())\n",
            "display(customers.describe())"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Calculate RFM Scores\n",
            "def calculate_rfm_score(value, quartiles, reverse=False):\n",
            "    '''Assign quintile scores (1-5).'''\n",
            "    if reverse:  # For Recency (lower is better)\n",
            "        if value <= quartiles[0.2]:\n",
            "            return 5\n",
            "        elif value <= quartiles[0.4]:\n",
            "            return 4\n",
            "        elif value <= quartiles[0.6]:\n",
            "            return 3\n",
            "        elif value <= quartiles[0.8]:\n",
            "            return 2\n",
            "        else:\n",
            "            return 1\n",
            "    else:  # For Frequency & Monetary (higher is better)\n",
            "        if value <= quartiles[0.2]:\n",
            "            return 1\n",
            "        elif value <= quartiles[0.4]:\n",
            "            return 2\n",
            "        elif value <= quartiles[0.6]:\n",
            "            return 3\n",
            "        elif value <= quartiles[0.8]:\n",
            "            return 4\n",
            "        else:\n",
            "            return 5\n",
            "\n",
            "# Calculate quintiles\n",
            "r_quintiles = customers['last_purchase_days'].quantile([0.2, 0.4, 0.6, 0.8])\n",
            "f_quintiles = customers['purchase_frequency'].quantile([0.2, 0.4, 0.6, 0.8])\n",
            "m_quintiles = customers['total_spend'].quantile([0.2, 0.4, 0.6, 0.8])\n",
            "\n",
            "# Apply RFM scoring\n",
            "customers['R_Score'] = customers['last_purchase_days'].apply(\n",
            "    lambda x: calculate_rfm_score(x, r_quintiles, reverse=True))\n",
            "customers['F_Score'] = customers['purchase_frequency'].apply(\n",
            "    lambda x: calculate_rfm_score(x, f_quintiles))\n",
            "customers['M_Score'] = customers['total_spend'].apply(\n",
            "    lambda x: calculate_rfm_score(x, m_quintiles))\n",
            "\n",
            "# Combined RFM Score\n",
            "customers['RFM_Score'] = (customers['R_Score'] * 100 + \n",
            "                          customers['F_Score'] * 10 + \n",
            "                          customers['M_Score'])\n",
            "\n",
            "print('\\n=== RFM Score Distribution ===')\n",
            "print(customers[['R_Score', 'F_Score', 'M_Score', 'RFM_Score']].describe())"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Customer Lifetime Value (CLV) Calculation\n",
            "# Simple CLV formula: (Avg Order Value × Purchase Frequency × Tenure) / Churn adjustment\n",
            "\n",
            "customers['CLV'] = (customers['avg_order_value'] * \n",
            "                    customers['purchase_frequency'] * \n",
            "                    (customers['tenure_months'] / 12)) * 0.8  # 20% churn adjustment\n",
            "\n",
            "# CLV Categories\n",
            "customers['CLV_Category'] = pd.qcut(customers['CLV'], \n",
            "                                     q=4, \n",
            "                                     labels=['Low', 'Medium', 'High', 'VIP'])\n",
            "\n",
            "print('\\n=== CLV Statistics ===')\n",
            "print(f'Mean CLV: ${customers[\"CLV\"].mean():,.2f}')\n",
            "print(f'Median CLV: ${customers[\"CLV\"].median():,.2f}')\n",
            "print(f'Total Customer Value: ${customers[\"CLV\"].sum():,.2f}')\n",
            "\n",
            "print('\\n=== CLV by Category ===')\n",
            "print(customers.groupby('CLV_Category')['CLV'].agg(['count', 'mean', 'sum']))"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Clustering Analysis\n",
            "# Prepare features for clustering\n",
            "cluster_features = ['R_Score', 'F_Score', 'M_Score', 'CLV', 'tenure_months']\n",
            "X = customers[cluster_features].copy()\n",
            "\n",
            "# Standardize\n",
            "scaler = StandardScaler()\n",
            "X_scaled = scaler.fit_transform(X)\n",
            "\n",
            "# Determine optimal k using Elbow + Silhouette\n",
            "inertias = []\n",
            "silhouette_scores = []\n",
            "K_range = range(2, 11)\n",
            "\n",
            "for k in K_range:\n",
            "    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)\n",
            "    kmeans.fit(X_scaled)\n",
            "    inertias.append(kmeans.inertia_)\n",
            "    silhouette_scores.append(silhouette_score(X_scaled, kmeans.labels_))\n",
            "\n",
            "print('\\n=== Clustering Quality Metrics ===')\n",
            "for k, sil in zip(K_range, silhouette_scores):\n",
            "    print(f'k={k}: Silhouette Score = {sil:.3f}')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Apply K-Means with optimal k=4\n",
            "optimal_k = 4\n",
            "kmeans = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)\n",
            "customers['Cluster'] = kmeans.fit_predict(X_scaled)\n",
            "\n",
            "# Cluster Profiling\n",
            "cluster_profile = customers.groupby('Cluster').agg({\n",
            "    'customer_id': 'count',\n",
            "    'last_purchase_days': 'mean',\n",
            "    'purchase_frequency': 'mean',\n",
            "    'total_spend': 'mean',\n",
            "    'CLV': 'mean',\n",
            "    'R_Score': 'mean',\n",
            "    'F_Score': 'mean',\n",
            "    'M_Score': 'mean'\n",
            "}).round(2)\n",
            "\n",
            "cluster_profile.columns = ['Count', 'Avg_Recency', 'Avg_Frequency', \n",
            "                            'Avg_Spend', 'Avg_CLV', 'Avg_R', 'Avg_F', 'Avg_M']\n",
            "\n",
            "print('\\n=== Cluster Profiles ===')\n",
            "display(cluster_profile)"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Segment Naming & Business Interpretation\n",
            "segment_names = {}\n",
            "for cluster in range(optimal_k):\n",
            "    profile = cluster_profile.loc[cluster]\n",
            "    \n",
            "    if profile['Avg_CLV'] > customers['CLV'].quantile(0.75):\n",
            "        if profile['Avg_Recency'] < 30:\n",
            "            segment_names[cluster] = 'Champions'\n",
            "        else:\n",
            "            segment_names[cluster] = 'At Risk VIP'\n",
            "    elif profile['Avg_CLV'] > customers['CLV'].median():\n",
            "        if profile['Avg_Frequency'] > customers['purchase_frequency'].median():\n",
            "            segment_names[cluster] = 'Loyal Customers'\n",
            "        else:\n",
            "            segment_names[cluster] = 'Potential Loyalists'\n",
            "    else:\n",
            "        if profile['Avg_Recency'] > 60:\n",
            "            segment_names[cluster] = 'Lost'\n",
            "        else:\n",
            "            segment_names[cluster] = 'New/Low Value'\n",
            "\n",
            "customers['Segment'] = customers['Cluster'].map(segment_names)\n",
            "\n",
            "print('\\n=== Segment Distribution ===')\n",
            "print(customers['Segment'].value_counts())"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Comprehensive Visualizations\n",
            "fig = plt.figure(figsize=(20, 16))\n",
            "gs = fig.add_gridspec(4, 3, hspace=0.35, wspace=0.3)\n",
            "\n",
            "# 1. RFM 3D Scatter (using PCA for visualization)\n",
            "ax1 = fig.add_subplot(gs[0, 0], projection='3d')\n",
            "scatter = ax1.scatter(customers['R_Score'], customers['F_Score'], customers['M_Score'],\n",
            "                      c=customers['Cluster'], cmap='viridis', s=20, alpha=0.6)\n",
            "ax1.set_xlabel('Recency Score')\n",
            "ax1.set_ylabel('Frequency Score')\n",
            "ax1.set_zlabel('Monetary Score')\n",
            "ax1.set_title('RFM 3D Scatter Plot', fontweight='bold')\n",
            "plt.colorbar(scatter, ax=ax1, label='Cluster')\n",
            "\n",
            "# 2. Elbow Method\n",
            "ax2 = fig.add_subplot(gs[0, 1])\n",
            "ax2.plot(K_range, inertias, 'bo-', linewidth=2, markersize=8)\n",
            "ax2.set_xlabel('Number of Clusters (k)')\n",
            "ax2.set_ylabel('Inertia')\n",
            "ax2.set_title('Elbow Method', fontweight='bold')\n",
            "ax2.grid(alpha=0.3)\n",
            "ax2.axvline(optimal_k, color='red', linestyle='--', label=f'Optimal k={optimal_k}')\n",
            "ax2.legend()\n",
            "\n",
            "# 3. Silhouette Scores\n",
            "ax3 = fig.add_subplot(gs[0, 2])\n",
            "ax3.plot(K_range, silhouette_scores, 'ro-', linewidth=2, markersize=8)\n",
            "ax3.set_xlabel('Number of Clusters (k)')\n",
            "ax3.set_ylabel('Silhouette Score')\n",
            "ax3.set_title('Silhouette Analysis', fontweight='bold')\n",
            "ax3.grid(alpha=0.3)\n",
            "ax3.axvline(optimal_k, color='blue', linestyle='--')\n",
            "\n",
            "# 4. Segment Size pie chart\n",
            "ax4 = fig.add_subplot(gs[1, 0])\n",
            "segment_counts = customers['Segment'].value_counts()\n",
            "ax4.pie(segment_counts, labels=segment_counts.index, autopct='%1.1f%%', startangle=90)\n",
            "ax4.set_title('Customer Segments Distribution', fontweight='bold')\n",
            "\n",
            "# 5. CLV by Segment\n",
            "ax5 = fig.add_subplot(gs[1, 1])\n",
            "clv_by_segment = customers.groupby('Segment')['CLV'].mean().sort_values(ascending=True)\n",
            "colors = plt.cm.RdYlGn(np.linspace(0.3, 0.9, len(clv_by_segment)))\n",
            "clv_by_segment.plot(kind='barh', ax=ax5, color=colors, edgecolor='black')\n",
            "ax5.set_xlabel('Average CLV ($)')\n",
            "ax5.set_title('CLV by Segment', fontweight='bold')\n",
            "ax5.grid(axis='x', alpha=0.3)\n",
            "\n",
            "# 6. RFM Heatmap\n",
            "ax6 = fig.add_subplot(gs[1, 2])\n",
            "rfm_pivot = customers.groupby('Segment')[['R_Score', 'F_Score', 'M_Score']].mean()\n",
            "sns.heatmap(rfm_pivot.T, annot=True, fmt='.2f', cmap='YlGnBu', ax=ax6, cbar_kws={'label': 'Score'})\n",
            "ax6.set_title('RFM Scores by Segment', fontweight='bold')\n",
            "\n",
            "# 7. CLV Distribution\n",
            "ax7 = fig.add_subplot(gs[2, :])\n",
            "for segment in customers['Segment'].unique():\n",
            "    subset = customers[customers['Segment'] == segment]['CLV']\n",
            "    ax7.hist(subset, bins=30, alpha=0.5, label=segment, edgecolor='black')\n",
            "ax7.set_xlabel('Customer Lifetime Value ($)')\n",
            "ax7.set_ylabel('Frequency')\n",
            "ax7.set_title('CLV Distribution by Segment', fontweight='bold')\n",
            "ax7.legend()\n",
            "ax7.grid(alpha=0.3)\n",
            "\n",
            "# 8. Segment Value Matrix\n",
            "ax8 = fig.add_subplot(gs[3, 0])\n",
            "segment_value = customers.groupby('Segment').agg({\n",
            "    'CLV': 'sum',\n",
            "    'customer_id': 'count'\n",
            "})\n",
            "segment_value.columns = ['Total_CLV', 'Customer_Count']\n",
            "segment_value = segment_value.sort_values('Total_CLV', ascending=True)\n",
            "segment_value['Total_CLV'].plot(kind='barh', ax=ax8, color='teal', edgecolor='black')\n",
            "ax8.set_xlabel('Total Segment Value ($)')\n",
            "ax8.set_title('Revenue Contribution by Segment', fontweight='bold')\n",
            "ax8.grid(axis='x', alpha=0.3)\n",
            "\n",
            "# 9. Recency vs Frequency colored by Monetary\n",
            "ax9 = fig.add_subplot(gs[3, 1])\n",
            "scatter = ax9.scatter(customers['last_purchase_days'], customers['purchase_frequency'],\n",
            "                      c=customers['total_spend'], cmap='plasma', s=30, alpha=0.6)\n",
            "ax9.set_xlabel('Recency (days since last purchase)')\n",
            "ax9.set_ylabel('Frequency (# purchases)')\n",
            "ax9.set_title('Recency vs Frequency (colored by Spend)', fontweight='bold')\n",
            "plt.colorbar(scatter, ax=ax9, label='Total Spend ($)')\n",
            "ax9.grid(alpha=0.3)\n",
            "\n",
            "# 10. Summary Table\n",
            "ax10 = fig.add_subplot(gs[3, 2])\n",
            "ax10.axis('off')\n",
            "summary_data = [\n",
            "    ['Total Customers', f'{len(customers):,}'],\n",
            "    ['Total CLV', f'${customers[\"CLV\"].sum():,.0f}'],\n",
            "    ['Avg CLV', f'${customers[\"CLV\"].mean():,.2f}'],\n",
            "    ['# Segments', f'{customers[\"Segment\"].nunique()}'],\n",
            "    ['Champions %', f'{(customers[\"Segment\"] == \"Champions\").sum() / len(customers) * 100:.1f}%']\n",
            "]\n",
            "table = ax10.table(cellText=summary_data, colLabels=['Metric', 'Value'],\n",
            "                   cellLoc='left', loc='center', bbox=[0, 0.2, 1, 0.6])\n",
            "table.auto_set_font_size(False)\n",
            "table.set_fontsize(10)\n",
            "table.scale(1, 2.5)\n",
            "ax10.set_title('Summary Metrics', fontweight='bold', pad=20)\n",
            "\n",
            "plt.suptitle('Customer Segmentation Analysis', fontsize=18, fontweight='bold', y=0.995)\n",
            "plt.show()"
        ]},
        
        {"cell_type": "markdown", "metadata": {}, "source": [
            "## 🎯 Segment Strategies & Marketing Recommendations\n\n",
            "### Segment Profiles & Actions\n\n",
            "#### 1. Champions (High CLV, Recent, Frequent)\n",
            "**Characteristics**: Best customers - recent purchases, high frequency, high spend\n",
            "**Strategy**:\n",
            "- VIP rewards program\n",
            "- Early access to new products\n",
            "- Personalized thank-you campaigns\n",
            "- Referral incentives (they're your best advocates)\n\n",
            "**Expected ROI**: 300-500% (retention focus)\n\n",
            "#### 2. Loyal Customers (High Frequency, Medium CLV)\n",
            "**Characteristics**: Regular buyers but not the highest spenders\n",
            "**Strategy**:\n",
            "- Upsell premium products\n",
            "- Cross-sell complementary items\n",
            "- Loyalty point multipliers\n",
            "- Exclusive member-only sales\n\n",
            "**Expected ROI**: 200-300%\n\n",
            "#### 3. At Risk VIP (High Past Value, Low Recent Activity)\n",
            "**Characteristics**: Used to be valuable but haven't purchased recently\n",
            "**Strategy**:\n",
            "- Win-back campaigns with special offers\n",
            "- \"We miss you\" personalized emails\n",
            "- Survey to understand why they left\n",
            "- Limited-time comeback discounts\n\n",
            "**Expected ROI**: 150-250% (recovery focus)\n\n",
            "#### 4. Potential Loyalists (Medium Engagement)\n",
            "**Characteristics**: Showing promise but need nurturing\n",
            "**Strategy**:\n",
            "- Engagement campaigns (newsletters, tips)\n",
            "- Onboarding sequences\n",
            "- First-purchase incentives for second purchase\n",
            "- Build product familiarity\n\n",
            "**Expected ROI**: 100-200%\n\n",
            "#### 5. New/Low Value\n",
            "**Characteristics**: Recent joiners or low engagement\n",
            "**Strategy**:\n",
            "- Automated welcome series\n",
            "- Educational content\n",
            "- Incentivized first purchases\n",
            "- Monitor for early churn signals\n\n",
            "**Expected ROI**: 50-150%\n\n",
            "#### 6. Lost (Inact ive, Low Recent)\n",
            "**Characteristics**: Haven't purchased in long time\n",
            "**Strategy**:\n",
            "- Low-cost reactivation attempts\n",
            "- Sunset campaigns (final offer)\n",
            "- Learn from exit surveys\n",
            "- Consider suppressing to save costs\n\n",
            "**Expected ROI**: 25-75% (cost-minimization)\n\n",
            "### Budget Allocation\n",
            "Based on segment value and ROI potential:\n",
            "1. **Champions**: 30% of marketing budget\n",
            "2. **Loyal Customers**: 25%\n",
            "3. **At Risk VIP**: 20%\n",
            "4. **Potential Loyalists**: 15%\n",
            "5. **New/Low Value**: 8%\n",
            "6. **Lost**: 2%\n\n",
            "### Key Performance Indicators (KPIs)\n",
            "- **Segment Migration**: Track upward movement (e.g., New → Loyal)\n",
            "- **Churn Rate by Segment**: Especially monitor Champions\n",
            "- **CLV Growth**: Year-over-year CLV increase\n",
            "- **Campaign Response Rates**: By segment\n",
            "- **Revenue per Segment**: Monthly tracking"
        ]}
    ]
    
    return json.dumps(create_notebook(cells), indent=1)

print("Customer Segmentation generator created")
print("Features: RFM scoring, CLV calculation, K-means clustering, 10 visualizations")
