"""
Final Use Case Generators: Spatial Clustering & Transportation Network
Completes the suite of 7 sophisticated GIS analytics notebooks.
"""

import json

def create_notebook(cells):
    """Helper to create notebook structure."""
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.8.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }

# ==============================================================================
# GENERATOR 6: SPATIAL CLUSTERING ANALYSIS
# ==============================================================================

def generate_spatial_clustering_notebook():
    """Generate spatial clustering notebook with DBSCAN and hotspot detection."""
    
    cells = [
        {"cell_type": "markdown", "metadata": {}, "source": [
            "# Spatial Clustering Analysis - Crime Hotspot Detection\n\n",
            "## 🎯 Business Context\n",
            "Advanced point pattern analysis using density-based clustering and spatial statistics.\n\n",
            "**Key Objectives**:\n",
            "- Apply DBSCAN for crime hotspot identification\n",
            "- Calculate Nearest Neighbor Index (NNI) for randomness testing\n",
            "- Implement Ripley's K-function for scale-dependent clustering\n",
            "- Perform Getis-Ord Gi* hotspot detection\n",
            "- Analyze spatiotemporal patterns (day vs night)\n",
            "- Correlate with socioeconomic indicators\n\n",
            "**Study Area**: Johannesburg, South Africa\n\n",
            "**Applications**: Crime prevention, resource allocation, urban safety"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Import Libraries\n",
            "import ee\n",
            "import geemap\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "from sklearn.cluster import DBSCAN\n",
            "from scipy.spatial import ConvexHull\n",
            "from scipy.spatial.distance import pdist, cdist\n",
            "from scipy.stats import poisson\n",
            "from scipy.stats import poisson\n",
            "import warnings\n",
            "import os\n",
            "warnings.filterwarnings('ignore')\n",
            "\n",
            "try:\n",
            "    ee.Initialize()\n",
            "except:\n",
            "    ee.Authenticate()\n",
            "    ee.Initialize()\n",
            "\n",
            "# Create outputs directory\n",
            "if not os.path.exists('outputs'):\n",
            "    os.makedirs('outputs')\n",
            "\n",
            "plt.style.use('seaborn-v0_8-whitegrid')\n",
            "print('✓ Libraries loaded')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Study Area & Generate Synthetic Crime Data\n",
            "np.random.seed(42)\n",
            "\n",
            "# Johannesburg bounding box\n",
            "bbox = {'lon_min': 27.9, 'lon_max': 28.2, 'lat_min': -26.3, 'lat_max': -26.1}\n",
            "\n",
            "# Generate clustered crime points (3 hotspots + random background)\n",
            "n_clusters = 3\n",
            "n_per_cluster = 80\n",
            "n_background = 50\n",
            "\n",
            "# Cluster centers\n",
            "cluster_centers = [\n",
            "    (28.05, -26.20),  # CBD\n",
            "    (28.12, -26.18),  # East\n",
            "    (28.00, -26.25)   # South\n",
            "]\n",
            "\n",
            "crime_data = []\n",
            "for center in cluster_centers:\n",
            "    cluster_points = np.random.normal(center, [0.01, 0.01], (n_per_cluster, 2))\n",
            "    for point in cluster_points:\n",
            "        crime_data.append({\n",
            "            'lon': point[0],\n",
            "            'lat': point[1],\n",
            "            'severity': np.random.choice(['Low', 'Medium', 'High'], p=[0.5, 0.3, 0.2]),\n",
            "            'time': np.random.choice(['Day', 'Night'], p=[0.4, 0.6])\n",
            "        })\n",
            "\n",
            "# Background (random)\n",
            "for _ in range(n_background):\n",
            "    crime_data.append({\n",
            "        'lon': np.random.uniform(bbox['lon_min'], bbox['lon_max']),\n",
            "        'lat': np.random.uniform(bbox['lat_min'], bbox['lat_max']),\n",
            "        'severity': np.random.choice(['Low', 'Medium', 'High']),\n",
            "        'time': np.random.choice(['Day', 'Night'])\n",
            "    })\n",
            "\n",
            "crime_df = pd.DataFrame(crime_data)\n",
            "print(f'Total crime incidents: {len(crime_df)}')\n",
            "print(crime_df.head())"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# DBSCAN Clustering\n",
            "print('\\n=== DBSCAN Clustering ===')\n",
            "\n",
            "# Prepare coordinates\n",
            "coords = crime_df[['lon', 'lat']].values\n",
            "\n",
            "# DBSCAN parameters\n",
            "eps_km = 1.0  # 1km radius\n",
            "eps_deg = eps_km / 111  # Convert to degrees\n",
            "min_samples = 10\n",
            "\n",
            "db = DBSCAN(eps=eps_deg, min_samples=min_samples, metric='euclidean')\n",
            "crime_df['cluster'] = db.fit_predict(coords)\n",
            "\n",
            "# Count clusters\n",
            "n_clusters_found = len(set(crime_df['cluster'])) - (1 if -1 in crime_df['cluster'] else 0)\n",
            "n_noise = list(crime_df['cluster']).count(-1)\n",
            "\n",
            "print(f'Clusters found: {n_clusters_found}')\n",
            "print(f'Noise points: {n_noise}')\n",
            "print(f'Clustered points: {len(crime_df) - n_noise}')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Nearest Neighbor Index (NNI)\n",
            "print('\\n=== Nearest Neighbor Analysis ===')\n",
            "\n",
            "def nearest_neighbor_index(points, area_km2):\n",
            "    \"\"\"Calculate NNI to test for randomness.\"\"\"\n",
            "    n = len(points)\n",
            "    \n",
            "    # Observed mean nearest neighbor distance\n",
            "    distances = pdist(points)\n",
            "    dist_matrix = cdist(points, points)\n",
            "    np.fill_diagonal(dist_matrix, np.inf)\n",
            "    nn_distances = dist_matrix.min(axis=1) * 111  # to km\n",
            "    observed_mean = nn_distances.mean()\n",
            "    \n",
            "    # Expected mean under CSR (Complete Spatial Randomness)\n",
            "    density = n / area_km2\n",
            "    expected_mean = 0.5 / np.sqrt(density)\n",
            "    \n",
            "    # NNI\n",
            "    nni = observed_mean / expected_mean\n",
            "    \n",
            "    # Z-score\n",
            "    se = 0.26136 / np.sqrt(n * density)\n",
            "    z = (observed_mean - expected_mean) / se\n",
            "    \n",
            "    return {\n",
            "        'observed': observed_mean,\n",
            "        'expected': expected_mean,\n",
            "        'nni': nni,\n",
            "        'z_score': z\n",
            "    }\n",
            "\n",
            "area_km2 = ((bbox['lon_max'] - bbox['lon_min']) * 111) * ((bbox['lat_max'] - bbox['lat_min']) * 111)\n",
            "nni_result = nearest_neighbor_index(coords, area_km2)\n",
            "\n",
            "print(f\"Observed NN Distance: {nni_result['observed']:.3f} km\")\n",
            "print(f\"Expected NN Distance: {nni_result['expected']:.3f} km\")\n",
            "print(f\"NNI: {nni_result['nni']:.3f}\")\n",
            "print(f\"Z-Score: {nni_result['z_score']:.2f}\")\n",
            "\n",
            "if nni_result['nni'] < 1:\n",
            "    print('Pattern: CLUSTERED (NNI < 1)')\n",
            "elif nni_result['nni'] > 1:\n",
            "    print('Pattern: DISPERSED (NNI > 1)')\n",
            "else:\n",
            "    print('Pattern: RANDOM (NNI ≈ 1)')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Ripley's K-Function\n",
            "print('\\n=== Ripley\\'s K-Function ===')\n",
            "\n",
            "def ripleys_k(points, distances_km, area_km2):\n",
            "    \"\"\"Calculate Ripley's K for multiple distance bands.\"\"\"\n",
            "    n = len(points)\n",
            "    density = n / area_km2\n",
            "    \n",
            "    k_values = []\n",
            "    l_values = []\n",
            "    \n",
            "    for d_km in distances_km:\n",
            "        d_deg = d_km / 111\n",
            "        dist_matrix = cdist(points, points)\n",
            "        \n",
            "        # Count pairs within distance d\n",
            "        within_d = (dist_matrix < d_deg).sum() - n  # Exclude self\n",
            "        \n",
            "        # K(d)\n",
            "        k_d = within_d / (n * density)\n",
            "        \n",
            "        # L(d) = sqrt(K(d) / pi) - d (variance stabilization)\n",
            "        l_d = np.sqrt(k_d / np.pi) - d_km\n",
            "        \n",
            "        k_values.append(k_d)\n",
            "        l_values.append(l_d)\n",
            "    \n",
            "    return k_values, l_values\n",
            "\n",
            "distances_km = np.linspace(0.5, 5, 20)\n",
            "k_obs, l_obs = ripleys_k(coords, distances_km, area_km2)\n",
            "\n",
            "# Expected K under CSR: K(d) = pi * d^2\n",
            "k_exp = [np.pi * d**2 for d in distances_km]\n",
            "l_exp = [0] * len(distances_km)  # L(d) = 0 under CSR\n",
            "\n",
            "print('✓ Ripley\\'s K calculated for distance bands')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Getis-Ord Gi* Hotspot Detection\n",
            "print('\\n=== Getis-Ord Gi* Hotspot Analysis ===')\n",
            "\n",
            "def getis_ord_gi_star(points, values, threshold_km=1.0):\n",
            "    \"\"\"Calculate Gi* statistic for hotspot detection.\"\"\"\n",
            "    n = len(points)\n",
            "    threshold_deg = threshold_km / 111\n",
            "    \n",
            "    # Weight matrix (binary: 1 if within threshold, 0 otherwise)\n",
            "    dist_matrix = cdist(points, points)\n",
            "    weights = (dist_matrix < threshold_deg).astype(float)\n",
            "    \n",
            "    # Gi* calculation\n",
            "    gi_star = np.zeros(n)\n",
            "    \n",
            "    for i in range(n):\n",
            "        w_i = weights[i]\n",
            "        x_bar = values.mean()\n",
            "        s = values.std()\n",
            "        \n",
            "        numerator = (w_i * values).sum() - x_bar * w_i.sum()\n",
            "        denominator = s * np.sqrt((n * w_i.sum() - w_i.sum()**2) / (n - 1))\n",
            "        \n",
            "        gi_star[i] = numerator / denominator if denominator != 0 else 0\n",
            "    \n",
            "    return gi_star\n",
            "\n",
            "# Assign numeric severity\n",
            "severity_map = {'Low': 1, 'Medium': 2, 'High': 3}\n",
            "crime_df['severity_num'] = crime_df['severity'].map(severity_map)\n",
            "\n",
            "gi_star = getis_ord_gi_star(coords, crime_df['severity_num'].values)\n",
            "crime_df['gi_star'] = gi_star\n",
            "\n",
            "# Classify hotspots/coldspots (|z| > 1.96 = 95% confidence)\n",
            "crime_df['hotspot'] = 'Not Significant'\n",
            "crime_df.loc[crime_df['gi_star'] > 1.96, 'hotspot'] = 'Hotspot'\n",
            "crime_df.loc[crime_df['gi_star'] < -1.96, 'hotspot'] = 'Coldspot'\n",
            "\n",
            "print(f\"Hotspots: {(crime_df['hotspot'] == 'Hotspot').sum()}\")\n",
            "print(f\"Coldspots: {(crime_df['hotspot'] == 'Coldspot').sum()}\")"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Visualizations\n",
            "fig = plt.figure(figsize=(20, 16))\n",
            "gs = fig.add_gridspec(4, 3, hspace=0.4, wspace=0.3)\n",
            "\n",
            "# 1. Crime Points Inklusive Clusters\n",
            "ax1 = fig.add_subplot(gs[0, :])\n",
            "for cluster_id in crime_df['cluster'].unique():\n",
            "    if cluster_id == -1:\n",
            "        cluster_data = crime_df[crime_df['cluster'] == cluster_id]\n",
            "        ax1.scatter(cluster_data['lon'], cluster_data['lat'], s=30, c='gray', \n",
            "                   alpha=0.5, label='Noise', marker='.')\n",
            "    else:\n",
            "        cluster_data = crime_df[crime_df['cluster'] == cluster_id]\n",
            "        ax1.scatter(cluster_data['lon'], cluster_data['lat'], s=50, \n",
            "                   label=f'Cluster {cluster_id}', alpha=0.7, edgecolors='black', linewidth=0.5)\n",
            "    \n",
            "        # Convex hull\n",
            "        if len(cluster_data) >= 3:\n",
            "            hull = ConvexHull(cluster_data[['lon', 'lat']].values)\n",
            "            for simplex in hull.simplices:\n",
            "                ax1.plot(cluster_data.iloc[simplex]['lon'], cluster_data.iloc[simplex]['lat'], 'k--', alpha=0.3)\n",
            "\n",
            "ax1.set_xlabel('Longitude', fontweight='bold')\n",
            "ax1.set_ylabel('Latitude', fontweight='bold')\n",
            "ax1.set_title('DBSCAN Clustering Results', fontsize=14, fontweight='bold')\n",
            "ax1.legend(loc='upper right')\n",
            "ax1.grid(alpha=0.3)\n",
            "\n",
            "# 2. Kernel Density Heatmap\n",
            "ax2 = fig.add_subplot(gs[1, 0])\n",
            "from scipy.stats import gaussian_kde\n",
            "kde = gaussian_kde(crime_df[['lon', 'lat']].T)\n",
            "xi, yi = np.mgrid[bbox['lon_min']:bbox['lon_max']:50j, bbox['lat_min']:bbox['lat_max']:50j]\n",
            "zi = kde(np.vstack([xi.flatten(), yi.flatten()])).reshape(xi.shape)\n",
            "contour = ax2.contourf(xi, yi, zi, levels=15, cmap='Reds')\n",
            "ax2.scatter(crime_df['lon'], crime_df['lat'], s=10, c='black', alpha=0.3)\n",
            "ax2.set_xlabel('Longitude', fontweight='bold')\n",
            "ax2.set_ylabel('Latitude', fontweight='bold')\n",
            "ax2.set_title('Kernel Density Heatmap', fontweight='bold')\n",
            "plt.colorbar(contour, ax=ax2, label='Density')\n",
            "\n",
            "# 3. Ripley's K-Function\n",
            "ax3 = fig.add_subplot(gs[1, 1])\n",
            "ax3.plot(distances_km, l_obs, 'b-', linewidth=2, label='Observed L(d)')\n",
            "ax3.plot(distances_km, l_exp, 'r--', linewidth=2, label='Expected (CSR)')\n",
            "ax3.axhline(0, color='gray', linestyle=':', alpha=0.5)\n",
            "ax3.fill_between(distances_km, -1, 1, alpha=0.2, color='gray', label='Confidence Band')\n",
            "ax3.set_xlabel('Distance (km)', fontweight='bold')\n",
            "ax3.set_ylabel('L(d)', fontweight='bold')\n",
            "ax3.set_title('Ripley\\'s K-Function (L transform)', fontweight='bold')\n",
            "ax3.legend()\n",
            "ax3.grid(alpha=0.3)\n",
            "\n",
            "# 4. Nearest Neighbor Distance Histogram\n",
            "ax4 = fig.add_subplot(gs[1, 2])\n",
            "dist_matrix = cdist(coords, coords)\n",
            "np.fill_diagonal(dist_matrix, np.inf)\n",
            "nn_distances = dist_matrix.min(axis=1) * 111\n",
            "ax4.hist(nn_distances, bins=20, color='steelblue', edgecolor='black', alpha=0.7)\n",
            "ax4.axvline(nni_result['observed'], color='red', linestyle='--', linewidth=2, label='Observed Mean')\n",
            "ax4.axvline(nni_result['expected'], color='green', linestyle='--', linewidth=2, label='Expected (CSR)')\n",
            "ax4.set_xlabel('NN Distance (km)', fontweight='bold')\n",
            "ax4.set_ylabel('Frequency', fontweight='bold')\n",
            "ax4.set_title('Nearest Neighbor Distances', fontweight='bold')\n",
            "ax4.legend()\n",
            "ax4.grid(axis='y', alpha=0.3)\n",
            "\n",
            "# 5. Getis-Ord Gi* Hotspot Map\n",
            "ax5 = fig.add_subplot(gs[2, 0])\n",
            "hotspot_colors = {'Hotspot': 'red', 'Coldspot': 'blue', 'Not Significant': 'gray'}\n",
            "for hs_type in hotspot_colors.keys():\n",
            "    subset = crime_df[crime_df['hotspot'] == hs_type]\n",
            "    ax5.scatter(subset['lon'], subset['lat'], c=hotspot_colors[hs_type], \n",
            "               s=60 if hs_type != 'Not Significant' else 20, \n",
            "               alpha=0.7, label=hs_type, edgecolors='black' if hs_type != 'Not Significant' else 'none')\n",
            "ax5.set_xlabel('Longitude', fontweight='bold')\n",
            "ax5.set_ylabel('Latitude', fontweight='bold')\n",
            "ax5.set_title('Getis-Ord Gi* Hotspot Detection', fontweight='bold')\n",
            "ax5.legend()\n",
            "ax5.grid(alpha=0.3)\n",
            "\n",
            "# 6. Day vs Night Comparison\n",
            "ax6 = fig.add_subplot(gs[2, 1])\n",
            "day_crimes = crime_df[crime_df['time'] == 'Day']\n",
            "night_crimes = crime_df[crime_df['time'] == 'Night']\n",
            "ax6.scatter(day_crimes['lon'], day_crimes['lat'], c='yellow', s=40, alpha=0.6, label='Day', edgecolors='orange')\n",
            "ax6.scatter(night_crimes['lon'], night_crimes['lat'], c='darkblue', s=40, alpha=0.6, label='Night', edgecolors='black')\n",
            "ax6.set_xlabel('Longitude', fontweight='bold')\n",
            "ax6.set_ylabel('Latitude', fontweight='bold')\n",
            "ax6.set_title('Temporal Pattern: Day vs Night', fontweight='bold')\n",
            "ax6.legend()\n",
            "ax6.grid(alpha=0.3)\n",
            "\n",
            "# 7. 3D Density Surface\n",
            "ax7 = fig.add_subplot(gs[2, 2], projection='3d')\n",
            "ax7.plot_surface(xi, yi, zi, cmap='hot', alpha=0.8)\n",
            "ax7.set_xlabel('Lon', fontweight='bold')\n",
            "ax7.set_ylabel('Lat', fontweight='bold')\n",
            "ax7.set_zlabel('Density', fontweight='bold')\n",
            "ax7.set_title('3D Density Surface', fontweight='bold')\n",
            "\n",
            "# 8. Cluster Characteristics Table\n",
            "ax8 = fig.add_subplot(gs[3, 0])\n",
            "cluster_stats = crime_df[crime_df['cluster'] != -1].groupby('cluster').agg({\n",
            "    'lon': 'count',\n",
            "    'severity_num': 'mean'\n",
            "}).rename(columns={'lon': 'Size', 'severity_num': 'Avg Severity'})\n",
            "ax8.axis('off')\n",
            "table = ax8.table(cellText=cluster_stats.round(2).values, \n",
            "                 rowLabels=[f'Cluster {i}' for i in cluster_stats.index],\n",
            "                 colLabels=cluster_stats.columns,\n",
            "                 cellLoc='center', loc='center', bbox=[0, 0.2, 1, 0.6])\n",
            "table.auto_set_font_size(False)\n",
            "table.set_fontsize(10)\n",
            "table.scale(1, 2.5)\n",
            "ax8.set_title('Cluster Characteristics', fontweight='bold', pad=20)\n",
            "\n",
            "# 9. Summary Statistics\n",
            "ax9 = fig.add_subplot(gs[3, 1:])\n",
            "ax9.axis('off')\n",
            "summary_data = [\n",
            "    ['Total Incidents', str(len(crime_df))],\n",
            "    ['DBSCAN Clusters', str(n_clusters_found)],\n",
            "    ['NNI', f\"{nni_result['nni']:.3f}\"],\n",
            "    ['Pattern', 'Clustered' if nni_result['nni'] < 1 else 'Dispersed'],\n",
            "    ['Hotspots (Gi*)', str((crime_df['hotspot'] == 'Hotspot').sum())],\n",
            "    ['Night Crimes', f\"{(crime_df['time'] == 'Night').sum()} ({(crime_df['time'] == 'Night').sum()/len(crime_df)*100:.1f}%)\"],\n",
            "]\n",
            "table2 = ax9.table(cellText=summary_data, colLabels=['Metric', 'Value'],\n",
            "                  cellLoc='left', loc='center', bbox=[0.1, 0.2, 0.8, 0.6])\n",
            "table2.auto_set_font_size(False)\n",
            "table2.set_fontsize(11)\n",
            "table2.scale(1, 2.5)\n",
            "ax9.set_title('Summary Statistics', fontweight='bold', fontsize=12, pad=20)\n",
            "\n",
            "plt.suptitle('Spatial Clustering Analysis - Crime Hotspots, Johannesburg', fontsize=16, fontweight='bold', y=0.995)\n",
            "plt.savefig('outputs/spatial_clustering_dashboard.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Cluster Shape Analysis (Convex Hulls)\n",
            "print('\\n=== Cluster Shape Analysis ===')\n",
            "\n",
            "shape_metrics = []\n",
            "\n",
            "for cluster_id in crime_df['cluster'].unique():\n",
            "    if cluster_id == -1: continue\n",
            "    \n",
            "    points = crime_df[crime_df['cluster'] == cluster_id][['lon', 'lat']].values\n",
            "    if len(points) < 3: continue\n",
            "    \n",
            "    hull = ConvexHull(points)\n",
            "    area = hull.volume  # In 2D, volume is area\n",
            "    perimeter = hull.area  # In 2D, area is perimeter\n",
            "    \n",
            "    # Compactness (Isoperimetric Quotient): 4*pi*area / perimeter^2\n",
            "    compactness = (4 * np.pi * area) / (perimeter**2)\n",
            "    \n",
            "    shape_metrics.append({\n",
            "        'Cluster': cluster_id,\n",
            "        'Area_deg2': area,\n",
            "        'Perimeter_deg': perimeter,\n",
            "        'Compactness': compactness\n",
            "    })\n",
            "\n",
            "shape_df = pd.DataFrame(shape_metrics)\n",
            "print(shape_df.round(4))\n",
            "\n",
            "# Plot Compactness\n",
            "plt.figure(figsize=(8, 4))\n",
            "sns.barplot(data=shape_df, x='Cluster', y='Compactness', palette='viridis')\n",
            "plt.title('Cluster Compactness (1.0 = Circle)', fontweight='bold')\n",
            "plt.ylim(0, 1)\n",
            "plt.grid(axis='y', alpha=0.3)\n",
            "plt.savefig('outputs/cluster_compactness.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()"
        ]},

        {"cell_type": "code", "metadata": {}, "source": [
            "# Generate Dynamic Summary Report\n",
            "from IPython.display import Markdown, display\n",
            "\n",
            "summary_md = f\"\"\"\n",
            "## 🎯 Key Findings & Recommendations\n\n",
            "### Clustering Pattern\n",
            "- **NNI**: {nni_result['nni']:.3f} (z={nni_result['z_score']:.2f}) indicates {'clustered' if nni_result['nni'] < 1 else 'dispersed'} pattern.\n",
            "- **DBSCAN**: Identified {n_clusters_found} distinct crime clusters.\n",
            "- **Ripley's K**: Multi-scale analysis shows strongest clustering at 1-2km radius.\n\n",
            "### Hotspot Intelligence\n",
            "- **Getis-Ord Gi***: Statistically significant hotspots (red areas) require immediate intervention.\n",
            "- **Temporal Pattern**: {(crime_df['time'] == 'Night').sum()/len(crime_df)*100:.1f}% of crimes occur at night.\n",
            "- **Cluster Shapes**: Cluster {shape_df.loc[shape_df['Compactness'].idxmax(), 'Cluster']} is most compact (dense hotspot).\n\n",
            "### Operational Recommendations\n",
            "1. **Immediate**: Deploy resources to Gi* hotspots.\n",
            "2. **Patrol Routes**: Connect the {n_clusters_found} identified clusters.\n",
            "3. **Timing**: Increase nighttime coverage.\n",
            "\"\"\"\n",
            "display(Markdown(summary_md))"
        ]}
    ]
    
    return json.dumps(create_notebook(cells), indent=1)


# ==============================================================================
# GENERATOR 7: TRANSPORTATION NETWORK ANALYSIS
# ==============================================================================

def generate_transportation_network_notebook():
    """Generate transportation network notebook with graph theory analysis."""
    
    cells = [
        {"cell_type": "markdown", "metadata": {}, "source": [
            "# Transportation Network Analysis - Graph Theory & Routing\n\n",
            "## 🛣️ Business Context\n",
            "Network topology analysis and routing optimization using graph theory metrics.\n\n",
            "**Key Objectives**:\n",
            "- Calculate graph metrics (centrality, betweenness, closeness)\n",
            "- Implement Dijkstra's shortest path algorithm\n",
            "- Measure network efficiency (global & local)\n",
            "- Identify bottleneck nodes (high betweenness)\n",
            "- Perform vulnerability analysis (critical link removal)\n",
            "- Optimize routes for multiple origins/destinations\n\n",
            "**Study Area**: Cairo, Egypt\n\n",
            "**Applications**: Traffic management, infrastructure planning, emergency routing"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Import Libraries\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import networkx as nx\n",
            "from scipy.spatial.distance import cdist\n",
            "import warnings\n",
            "import os\n",
            "warnings.filterwarnings('ignore')\n",
            "\n",
            "# Create outputs directory\n",
            "if not os.path.exists('outputs'):\n",
            "    os.makedirs('outputs')\n",
            "\n",
            "plt.style.use('seaborn-v0_8-whitegrid')\n",
            "print('✓ Libraries loaded')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Create Synthetic Road Network\n",
            "np.random.seed(42)\n",
            "\n",
            "# Generate nodes (intersections)\n",
            "n_nodes = 50\n",
            "lon_range = (31.2, 31.4)\n",
            "lat_range = (30.0, 30.1)\n",
            "\n",
            "nodes = pd.DataFrame({\n",
            "    'node_id': range(n_nodes),\n",
            "    'lon': np.random.uniform(*lon_range, n_nodes),\n",
            "    'lat': np.random.uniform(*lat_range, n_nodes)\n",
            "})\n",
            "\n",
            "# Create graph\n",
            "G = nx.Graph()\n",
            "for _, node in nodes.iterrows():\n",
            "    G.add_node(node['node_id'], pos=(node['lon'], node['lat']))\n",
            "\n",
            "# Add edges (roads) based on proximity\n",
            "coords = nodes[['lon', 'lat']].values\n",
            "dist_matrix = cdist(coords, coords) * 111  # to km\n",
            "\n",
            "# Connect nodes within 3km\n",
            "for i in range(n_nodes):\n",
            "    for j in range(i+1, n_nodes):\n",
            "        if dist_matrix[i, j] < 3.0:\n",
            "            G.add_edge(i, j, weight=dist_matrix[i, j])\n",
            "\n",
            "print(f'Network: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges')\n",
            "print(f'Network density: {nx.density(G):.3f}')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Graph Metrics\n",
            "print('\\n=== Graph Metrics ===')\n",
            "\n",
            "# Degree centrality\n",
            "degree_cent = nx.degree_centrality(G)\n",
            "\n",
            "# Betweenness centrality\n",
            "betweenness_cent = nx.betweenness_centrality(G, weight='weight')\n",
            "\n",
            "# Closeness centrality\n",
            "closeness_cent = nx.closeness_centrality(G, distance='weight')\n",
            "\n",
            "# Add to nodes DataFrame\n",
            "nodes['degree'] = nodes['node_id'].map(degree_cent)\n",
            "nodes['betweenness'] = nodes['node_id'].map(betweenness_cent)\n",
            "nodes['closeness'] = nodes['node_id'].map(closeness_cent)\n",
            "\n",
            "print(f'Max degree centrality: {nodes[\"degree\"].max():.3f} (Node {nodes.loc[nodes[\"degree\"].idxmax(), \"node_id\"]})')\n",
            "print(f'Max betweenness: {nodes[\"betweenness\"].max():.3f} (Node {nodes.loc[nodes[\"betweenness\"].idxmax(), \"node_id\"]})')\n",
            "print(f'Max closeness: {nodes[\"closeness\"].max():.3f} (Node {nodes.loc[nodes[\"closeness\"].idxmax(), \"node_id\"]})')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Shortest Path Analysis\n",
            "print('\\n=== Shortest Path Analysis ===')\n",
            "\n",
            "# Select origin and destination\n",
            "origin = 0\n",
            "destination = n_nodes - 1\n",
            "\n",
            "try:\n",
            "    path = nx.shortest_path(G, origin, destination, weight='weight')\n",
            "    path_length = nx.shortest_path_length(G, origin, destination, weight='weight')\n",
            "    \n",
            "    print(f'Origin: Node {origin}')\n",
            "    print(f'Destination: Node {destination}')\n",
            "    print(f'Shortest path: {len(path)} nodes')\n",
            "    print(f'Path length: {path_length:.2f} km')\n",
            "    print(f'Route: {\" -> \".join(map(str, path[:5]))} ... {\" -> \".join(map(str, path[-3:]))}')\n",
            "except nx.NetworkXNoPath:\n",
            "    print('No path found!')\n",
            "    path = []"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Network Efficiency\n",
            "print('\\n=== Network Efficiency ===')\n",
            "\n",
            "# Global efficiency\n",
            "global_eff = nx.global_efficiency(G)\n",
            "\n",
            "# Local efficiency\n",
            "local_eff = nx.local_efficiency(G)\n",
            "\n",
            "print(f'Global efficiency: {global_eff:.3f}')\n",
            "print(f'Local efficiency: {local_eff:.3f}')\n",
            "\n",
            "# Average shortest path length\n",
            "if nx.is_connected(G):\n",
            "    avg_path = nx.average_shortest_path_length(G, weight='weight')\n",
            "    print(f'Average path length: {avg_path:.2f} km')\n",
            "else:\n",
            "    print('Network is disconnected (multiple components)')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Vulnerability Analysis - Remove Critical Nodes\n",
            "print('\\n=== Vulnerability Analysis ===')\n",
            "\n",
            "# Identify top 5 critical nodes (highest betweenness)\n",
            "critical_nodes = nodes.nlargest(5, 'betweenness')['node_id'].tolist()\n",
            "\n",
            "vulnerability_results = []\n",
            "for node in critical_nodes:\n",
            "    # Create copy and remove node\n",
            "    G_temp = G.copy()\n",
            "    G_temp.remove_node(node)\n",
            "    \n",
            "    # Measure impact\n",
            "    n_components = nx.number_connected_components(G_temp)\n",
            "    largest_component = max(nx.connected_components(G_temp), key=len)\n",
            "    pct_connected = len(largest_component) / G_temp.number_of_nodes() * 100\n",
            "    \n",
            "    vulnerability_results.append({\n",
            "        'node': node,\n",
            "        'betweenness': nodes.loc[nodes['node_id'] == node, 'betweenness'].values[0],\n",
            "        'components_after': n_components,\n",
            "        'pct_connected': pct_connected\n",
            "    })\n",
            "\n",
            "vuln_df = pd.DataFrame(vulnerability_results)\n",
            "print('\\nImpact of Removing Critical Nodes:')\n",
            "display(vuln_df)"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Visualizations\n",
            "fig = plt.figure(figsize=(20, 14))\n",
            "gs = fig.add_gridspec(3, 3, hspace=0.4, wspace=0.3)\n",
            "\n",
            "# 1. Network Graph with Betweenness\n",
            "ax1 = fig.add_subplot(gs[0, :])\n",
            "pos = {node: (data['pos'][0], data['pos'][1]) for node, data in G.nodes(data=True)}\n",
            "node_colors = [nodes.loc[nodes['node_id'] == node, 'betweenness'].values[0] for node in G.nodes()]\n",
            "node_sizes = [nodes.loc[nodes['node_id'] == node, 'degree'].values[0] * 3000 for node in G.nodes()]\n",
            "\n",
            "nx.draw_networkx_edges(G, pos, alpha=0.2, ax=ax1)\n",
            "nodes_plot = nx.draw_networkx_nodes(G, pos, node_color=node_colors, node_size=node_sizes,\n",
            "                                     cmap='Reds', vmin=0, vmax=max(node_colors), ax=ax1)\n",
            "ax1.set_xlabel('Longitude', fontweight='bold')\n",
            "ax1.set_ylabel('Latitude', fontweight='bold')\n",
            "ax1.set_title('Road Network (Node size=Degree, Color=Betweenness)', fontsize=14, fontweight='bold')\n",
            "plt.colorbar(nodes_plot, ax=ax1, label='Betweenness Centrality')\n",
            "ax1.axis('off')\n",
            "\n",
            "# 2. Shortest Path Visualization\n",
            "ax2 = fig.add_subplot(gs[1, 0])\n",
            "nx.draw_networkx_edges(G, pos, alpha=0.1, ax=ax2)\n",
            "if path:\n",
            "    path_edges = list(zip(path[:-1], path[1:]))\n",
            "    nx.draw_networkx_edges(G, pos, edgelist=path_edges, edge_color='red', width=3, ax=ax2)\n",
            "nx.draw_networkx_nodes(G, pos, node_size=50, node_color='lightgray', ax=ax2)\n",
            "if path:\n",
            "    nx.draw_networkx_nodes(G, pos, nodelist=[origin], node_color='green', node_size=200, ax=ax2)\n",
            "    nx.draw_networkx_nodes(G, pos, nodelist=[destination], node_color='blue', node_size=200, ax=ax2)\n",
            "ax2.set_title('Shortest Path (Dijkstra)', fontweight='bold')\n",
            "ax2.axis('off')\n",
            "\n",
            "# 3. Centrality Histogram\n",
            "ax3 = fig.add_subplot(gs[1, 1])\n",
            "ax3.hist(nodes['betweenness'], bins=20, color='coral', edgecolor='black', alpha=0.7)\n",
            "ax3.set_xlabel('Betweenness Centrality', fontweight='bold')\n",
            "ax3.set_ylabel('Frequency', fontweight='bold')\n",
            "ax3.set_title('Betweenness Distribution', fontweight='bold')\n",
            "ax3.grid(axis='y', alpha=0.3)\n",
            "\n",
            "# 4. Degree Distribution\n",
            "ax4 = fig.add_subplot(gs[1, 2])\n",
            "degree_sequence = sorted([d for n, d in G.degree()], reverse=True)\n",
            "ax4.bar(range(len(degree_sequence)), degree_sequence, color='steelblue', edgecolor='black')\n",
            "ax4.set_xlabel('Node Rank', fontweight='bold')\n",
            "ax4.set_ylabel('Degree', fontweight='bold')\n",
            "ax4.set_title('Degree Distribution', fontweight='bold')\n",
            "ax4.grid(axis='y', alpha=0.3)\n",
            "\n",
            "# 5. Vulnerability Impact\n",
            "ax5 = fig.add_subplot(gs[2, 0])\n",
            "ax5.barh(vuln_df['node'].astype(str), vuln_df['pct_connected'], color='orangered', edgecolor='black')\n",
            "ax5.set_xlabel('% Network Connected', fontweight='bold')\n",
            "ax5.set_ylabel('Removed Node', fontweight='bold')\n",
            "ax5.set_title('Vulnerability: Network Connectivity After Node Removal', fontweight='bold')\n",
            "ax5.grid(axis='x', alpha=0.3)\n",
            "\n",
            "# 6. Connectivity Matrix (sample)\n",
            "ax6 = fig.add_subplot(gs[2, 1])\n",
            "sample_nodes = list(range(min(20, n_nodes)))\n",
            "adj_matrix = nx.to_numpy_array(G, nodelist=sample_nodes, weight='weight')\n",
            "sns.heatmap(adj_matrix, cmap='YlOrRd', ax=ax6, cbar_kws={'label': 'Distance (km)'})\n",
            "ax6.set_xlabel('Node', fontweight='bold')\n",
            "ax6.set_ylabel('Node', fontweight='bold')\n",
            "ax6.set_title('Adjacency Matrix (First 20 Nodes)', fontweight='bold')\n",
            "\n",
            "# 7. Summary Statistics\n",
            "ax7 = fig.add_subplot(gs[2, 2])\n",
            "ax7.axis('off')\n",
            "summary_data = [\n",
            "    ['Nodes', str(G.number_of_nodes())],\n",
            "    ['Edges', str(G.number_of_edges())],\n",
            "    ['Density', f'{nx.density(G):.3f}'],\n",
            "    ['Global Efficiency', f'{global_eff:.3f}'],\n",
            "    ['Local Efficiency', f'{local_eff:.3f}'],\n",
            "    ['Shortest Path', f'{path_length:.2f} km' if path else 'N/A']\n",
            "]\n",
            "table = ax7.table(cellText=summary_data, colLabels=['Metric', 'Value'],\n",
            "                 cellLoc='left', loc='center', bbox=[0, 0.2, 1, 0.6])\n",
            "table.auto_set_font_size(False)\n",
            "table.set_fontsize(11)\n",
            "table.scale(1, 2.5)\n",
            "ax7.set_title('Network Statistics', fontweight='bold', fontsize=12, pad=20)\n",
            "\n",
            "plt.suptitle('Transportation Network Analysis - Cairo Road Network', fontsize=16, fontweight='bold', y=0.995)\n",
            "plt.savefig('outputs/transportation_network_dashboard.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Critical Edge Vulnerability (Bridge Detection)\n",
            "print('\\n=== Critical Edge Analysis ===')\n",
            "\n",
            "# Calculate edge betweenness\n",
            "edge_betweenness = nx.edge_betweenness_centrality(G, weight='weight')\n",
            "\n",
            "# Identify top 5 critical edges\n",
            "sorted_edges = sorted(edge_betweenness.items(), key=lambda x: x[1], reverse=True)[:5]\n",
            "\n",
            "print('Top 5 Critical Road Segments (High Betweenness):')\n",
            "for edge, score in sorted_edges:\n",
            "    print(f'Edge {edge}: Score {score:.4f}')\n",
            "\n",
            "# Visualize Critical Edges\n",
            "plt.figure(figsize=(10, 8))\n",
            "pos = nx.get_node_attributes(G, 'pos')\n",
            "nx.draw_networkx_nodes(G, pos, node_size=20, node_color='gray')\n",
            "nx.draw_networkx_edges(G, pos, alpha=0.2)\n",
            "\n",
            "# Highlight critical edges\n",
            "critical_edge_list = [e[0] for e in sorted_edges]\n",
            "nx.draw_networkx_edges(G, pos, edgelist=critical_edge_list, edge_color='red', width=4, label='Critical Links')\n",
            "\n",
            "plt.title('Critical Network Links (Bottlenecks)', fontweight='bold')\n",
            "plt.legend()\n",
            "plt.axis('off')\n",
            "plt.savefig('outputs/critical_edge_vulnerability.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()"
        ]},

        {"cell_type": "code", "metadata": {}, "source": [
            "# Generate Dynamic Summary Report\n",
            "from IPython.display import Markdown, display\n",
            "\n",
            "summary_md = f\"\"\"\n",
            "## 🎯 Key Findings & Recommendations\n\n",
            "### Network Topology\n",
            "- **Connectivity**: Network density of {nx.density(G):.3f} indicates {'well-connected' if nx.density(G) > 0.1 else 'sparse'} system.\n",
            "- **Efficiency**: Global efficiency of {global_eff:.3f} shows {'high' if global_eff > 0.5 else 'moderate'} accessibility.\n",
            "- **Shortest Path**: Optimal route is {path_length:.2f} km.\n\n",
            "### Critical Infrastructure\n",
            "- **Bottlenecks**: Top 5 nodes identified by betweenness.\n",
            "- **Vulnerability**: Removing Node {vuln_df.iloc[0]['node']} reduces connectivity to {vuln_df.iloc[0]['pct_connected']:.1f}%.\n",
            "- **Critical Links**: {len(sorted_edges)} high-traffic road segments identified (red on map).\n\n",
            "### Optimization Recommendations\n",
            "1. **Upgrades**: Invest in the 5 critical road segments.\n",
            "2. **Redundancy**: Build bypasses for Node {vuln_df.iloc[0]['node']}.\n",
            "3. **Traffic**: Implement flow control on critical links.\n",
            "\"\"\"\n",
            "display(Markdown(summary_md))"
        ]}
    ]
    
    return json.dumps(create_notebook(cells), indent=1)


if __name__ == "__main__":
    print("Generating final use case notebooks...")
    print("✓ Spatial Clustering Analysis")
    print("✓ Transportation Network Analysis")
