"""
Geospatial Time Series Analysis Generator
Creates sophisticated notebook for vegetation dynamics with Mann-Kendall trend detection
"""

import json

def create_notebook(cells):
    """Helper to create notebook structure."""
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.8.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }

def generate_geospatial_timeseries_notebook():
    """Generate comprehensive geospatial time series analysis notebook."""
    
    cells = [
        {"cell_type": "markdown", "metadata": {}, "source": [
            "# Geospatial Time Series Analysis - Vegetation Dynamics Monitoring\n\n",
            "## 📈 Business Context\n",
            "Analyze long-term vegetation trends using MODIS NDVI time series with advanced statistical methods.\n\n",
            "**Key Objectives**:\n",
            "- Detect greening and browning trends using Mann-Kendall test\n",
            "- Quantify trend magnitude with Sen's slope estimator\n",
            "- Perform seasonal decomposition (trend, seasonal, residual)\n",
            "- Analyze rainfall-NDVI correlation\n",
            "- Identify drought events through anomaly detection\n",
            "- Extract vegetation phenology metrics\n\n",
            "**Study Area**: Sahel Region (West Africa)\n\n",
            "**Applications**: Climate change monitoring, drought early warning, ecosystem health assessment"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Import Libraries\n",
            "import ee\n",
            "import geemap\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "from scipy import stats\n",
            "from statsmodels.tsa.seasonal import seasonal_decompose\n",
            "from statsmodels.tsa.seasonal import seasonal_decompose\n",
            "import warnings\n",
            "import os\n",
            "warnings.filterwarnings('ignore')\n",
            "\n",
            "try:\n",
            "    ee.Initialize()\n",
            "except:\n",
            "    ee.Authenticate()\n",
            "    ee.Initialize()\n",
            "\n",
            "# Create outputs directory\n",
            "if not os.path.exists('outputs'):\n",
            "    os.makedirs('outputs')\n",
            "\n",
            "plt.style.use('seaborn-v0_8-darkgrid')\n",
            "print('✓ Libraries loaded successfully')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Define Study Area - Sahel Region\n",
            "sahel_region = ee.Geometry.Rectangle([-5, 12, 5, 16])\n",
            "\n",
            "# Time period: 2010-2024 (14 years)\n",
            "start_date = '2010-01-01'\n",
            "end_date = '2024-01-01'\n",
            "\n",
            "print(f'Study Area: {sahel_region.area().divide(1e6).getInfo():.2f} km²')\n",
            "print(f'Analysis Period: {start_date} to {end_date}')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Load MODIS NDVI Data (16-day composite)\n",
            "print('Loading MODIS NDVI data...')\n",
            "\n",
            "modis_ndvi = ee.ImageCollection('MODIS/061/MOD13A1') \\\n",
            "    .filterDate(start_date, end_date) \\\n",
            "    .filterBounds(sahel_region) \\\n",
            "    .select('NDVI')\n",
            "\n",
            "# Scale factor: 0.0001\n",
            "def scale_ndvi(image):\n",
            "    return image.multiply(0.0001).copyProperties(image, ['system:time_start'])\n",
            "\n",
            "ndvi_scaled = modis_ndvi.map(scale_ndvi)\n",
            "\n",
            "print(f'NDVI images: {ndvi_scaled.size().getInfo()}')\n",
            "\n",
            "# Load CHIRPS Precipitation Data\n",
            "print('Loading CHIRPS precipitation data...')\n",
            "\n",
            "chirps = ee.ImageCollection('UCSB-CHG/CHIRPS/DAILY') \\\n",
            "    .filterDate(start_date, end_date) \\\n",
            "    .filterBounds(sahel_region)\n",
            "\n",
            "# Aggregate to monthly\n",
            "def monthly_precip(year, month):\n",
            "    start = ee.Date.fromYMD(year, month, 1)\n",
            "    end = start.advance(1, 'month')\n",
            "    return chirps.filterDate(start, end).sum() \\\n",
            "        .set('system:time_start', start.millis()) \\\n",
            "        .set('year', year).set('month', month)\n",
            "\n",
            "years = ee.List.sequence(2010, 2023)\n",
            "months = ee.List.sequence(1, 12)\n",
            "\n",
            "monthly_rainfall = ee.ImageCollection.fromImages(\n",
            "    years.map(lambda y: months.map(lambda m: monthly_precip(y, m))).flatten()\n",
            ")\n",
            "\n",
            "print(f'Monthly rainfall images: {monthly_rainfall.size().getInfo()}')\n",
            "print('✓ All datasets loaded')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Extract Time Series for Sample Point\n",
            "# Select a representative point in the Sahel\n",
            "sample_point = ee.Geometry.Point([0.0, 14.0])\n",
            "\n",
            "# Extract NDVI time series\n",
            "def extract_ndvi(image):\n",
            "    value = image.reduceRegion(\n",
            "        reducer=ee.Reducer.mean(),\n",
            "        geometry=sample_point.buffer(5000),\n",
            "        scale=500\n",
            "    ).get('NDVI')\n",
            "    return ee.Feature(None, {\n",
            "        'date': ee.Date(image.get('system:time_start')).format('YYYY-MM-dd'),\n",
            "        'ndvi': value\n",
            "    })\n",
            "\n",
            "ndvi_ts = ndvi_scaled.map(extract_ndvi).getInfo()['features']\n",
            "ndvi_df = pd.DataFrame([f['properties'] for f in ndvi_ts])\n",
            "ndvi_df['date'] = pd.to_datetime(ndvi_df['date'])\n",
            "ndvi_df = ndvi_df.dropna().sort_values('date').set_index('date')\n",
            "\n",
            "# Extract rainfall time series (monthly)\n",
            "def extract_rain(image):\n",
            "    value = image.reduceRegion(\n",
            "        reducer=ee.Reducer.mean(),\n",
            "        geometry=sample_point.buffer(5000),\n",
            "        scale=5000\n",
            "    ).get('precipitation')\n",
            "    return ee.Feature(None, {\n",
            "        'date': ee.Date(image.get('system:time_start')).format('YYYY-MM'),\n",
            "        'rainfall': value\n",
            "    })\n",
            "\n",
            "rain_ts = monthly_rainfall.map(extract_rain).getInfo()['features']\n",
            "rain_df = pd.DataFrame([f['properties'] for f in rain_ts])\n",
            "rain_df['date'] = pd.to_datetime(rain_df['date'])\n",
            "rain_df = rain_df.dropna().sort_values('date').set_index('date')\n",
            "\n",
            "print(f'NDVI observations: {len(ndvi_df)}')\n",
            "print(f'Rainfall observations: {len(rain_df)}')\n",
            "print('\\nNDVI Statistics:')\n",
            "print(ndvi_df.describe())"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Mann-Kendall Trend Test\n",
            "def mann_kendall_test(data):\n",
            "    \"\"\"Perform Mann-Kendall trend test.\"\"\"\n",
            "    n = len(data)\n",
            "    s = 0\n",
            "    \n",
            "    for i in range(n-1):\n",
            "        for j in range(i+1, n):\n",
            "            s += np.sign(data[j] - data[i])\n",
            "    \n",
            "    # Variance\n",
            "    var_s = n * (n - 1) * (2 * n + 5) / 18\n",
            "    \n",
            "    # Z-statistic\n",
            "    if s > 0:\n",
            "        z = (s - 1) / np.sqrt(var_s)\n",
            "    elif s < 0:\n",
            "        z = (s + 1) / np.sqrt(var_s)\n",
            "    else:\n",
            "        z = 0\n",
            "    \n",
            "    # P-value (two-tailed)\n",
            "    p = 2 * (1 - stats.norm.cdf(abs(z)))\n",
            "    \n",
            "    # Trend\n",
            "    if p < 0.05:\n",
            "        trend = 'Significant increasing' if z > 0 else 'Significant decreasing'\n",
            "    else:\n",
            "        trend = 'No significant trend'\n",
            "    \n",
            "    return {'z': z, 'p': p, 'trend': trend}\n",
            "\n",
            "# Sen's Slope Estimator\n",
            "def sens_slope(data, dates):\n",
            "    \"\"\"Calculate Sen's slope (median of all pairwise slopes).\"\"\"\n",
            "    n = len(data)\n",
            "    slopes = []\n",
            "    \n",
            "    for i in range(n-1):\n",
            "        for j in range(i+1, n):\n",
            "            delta_y = data[j] - data[i]\n",
            "            delta_x = (dates[j] - dates[i]).days\n",
            "            if delta_x != 0:\n",
            "                slopes.append(delta_y / delta_x)\n",
            "    \n",
            "    return np.median(slopes) if slopes else 0\n",
            "\n",
            "# Apply tests\n",
            "print('\\n=== Mann-Kendall Trend Analysis ===')\n",
            "mk_result = mann_kendall_test(ndvi_df['ndvi'].values)\n",
            "print(f'Z-statistic: {mk_result[\"z\"]:.4f}')\n",
            "print(f'P-value: {mk_result[\"p\"]:.4f}')\n",
            "print(f'Trend: {mk_result[\"trend\"]}')\n",
            "\n",
            "sens = sens_slope(ndvi_df['ndvi'].values, ndvi_df.index.to_series())\n",
            "print(f\"\\nSen's Slope: {sens:.6f} NDVI/day\")\n",
            "print(f\"Annual trend: {sens * 365:.4f} NDVI/year\")"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Seasonal Decomposition\n",
            "print('\\n=== Seasonal Decomposition ===')\n",
            "\n",
            "# Resample to monthly for cleaner decomposition\n",
            "ndvi_monthly = ndvi_df.resample('M').mean()\n",
            "\n",
            "# Decompose (additive model)\n",
            "decomposition = seasonal_decompose(ndvi_monthly['ndvi'], model='additive', period=12)\n",
            "\n",
            "trend = decomposition.trend\n",
            "seasonal = decomposition.seasonal\n",
            "residual = decomposition.resid\n",
            "\n",
            "print('✓ Decomposition complete')\n",
            "print(f'Trend range: {trend.min():.3f} to {trend.max():.3f}')\n",
            "print(f'Seasonal amplitude: {seasonal.max() - seasonal.min():.3f}')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# NDVI-Rainfall Correlation\n",
            "print('\\n=== NDVI-Rainfall Correlation ===')\n",
            "\n",
            "# Align datasets (monthly)\n",
            "merged = pd.merge(\n",
            "    ndvi_monthly,\n",
            "    rain_df,\n",
            "    left_index=True,\n",
            "    right_index=True,\n",
            "    how='inner'\n",
            ")\n",
            "\n",
            "correlation, p_value = stats.pearsonr(merged['ndvi'], merged['rainfall'])\n",
            "print(f'Pearson correlation: {correlation:.3f}')\n",
            "print(f'P-value: {p_value:.4f}')\n",
            "\n",
            "if p_value < 0.05:\n",
            "    print(f'✓ Significant {\"positive\" if correlation > 0 else \"negative\"} correlation')\n",
            "else:\n",
            "    print('✗ No significant correlation')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Anomaly Detection - Drought Events\n",
            "print('\\n=== Drought Event Detection ===')\n",
            "\n",
            "# Calculate z-scores\n",
            "ndvi_monthly['z_score'] = (ndvi_monthly['ndvi'] - ndvi_monthly['ndvi'].mean()) / ndvi_monthly['ndvi'].std()\n",
            "\n",
            "# Drought: z-score < -1.5\n",
            "drought_events = ndvi_monthly[ndvi_monthly['z_score'] < -1.5]\n",
            "\n",
            "print(f'Drought events detected: {len(drought_events)}')\n",
            "if len(drought_events) > 0:\n",
            "    print('\\nDrought periods:')\n",
            "    for date, row in drought_events.iterrows():\n",
            "        print(f'  {date.strftime(\"%Y-%m\")}: NDVI={row[\"ndvi\"]:.3f}, z={row[\"z_score\"]:.2f}')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Phenology Metrics\n",
            "print('\\n=== Vegetation Phenology Metrics ===')\n",
            "\n",
            "# Calculate annual metrics\n",
            "phenology = []\n",
            "for year in range(2010, 2024):\n",
            "    year_data = ndvi_df[ndvi_df.index.year == year]['ndvi']\n",
            "    \n",
            "    if len(year_data) > 0:\n",
            "        # Peak NDVI (maximum)\n",
            "        peak_ndvi = year_data.max()\n",
            "        peak_date = year_data.idxmax()\n",
            "        \n",
            "        # Green-up (first time NDVI > threshold)\n",
            "        threshold = year_data.mean()\n",
            "        greenup = year_data[year_data > threshold].index.min() if any(year_data > threshold) else None\n",
            "        \n",
            "        # Senescence (last time NDVI > threshold)\n",
            "        senescence = year_data[year_data > threshold].index.max() if any(year_data > threshold) else None\n",
            "        \n",
            "        # Growing season length\n",
            "        gsl = (senescence - greenup).days if greenup and senescence else 0\n",
            "        \n",
            "        phenology.append({\n",
            "            'Year': year,\n",
            "            'Peak_NDVI': peak_ndvi,\n",
            "            'Peak_DOY': peak_date.dayofyear if peak_date else np.nan,\n",
            "            'Greenup_DOY': greenup.dayofyear if greenup else np.nan,\n",
            "            'Senescence_DOY': senescence.dayofyear if senescence else np.nan,\n",
            "            'Growing_Season_Length': gsl\n",
            "        })\n",
            "\n",
            "pheno_df = pd.DataFrame(phenology)\n",
            "print(pheno_df)"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Visualizations - Part 1: Time Series\n",
            "fig = plt.figure(figsize=(20, 14))\n",
            "gs = fig.add_gridspec(4, 2, hspace=0.4, wspace=0.3)\n",
            "\n",
            "# 1. Full NDVI Time Series with Trend\n",
            "ax1 = fig.add_subplot(gs[0, :])\n",
            "ax1.plot(ndvi_df.index, ndvi_df['ndvi'], color='green', alpha=0.6, linewidth=0.8, label='NDVI')\n",
            "ax1.plot(trend.index, trend, color='red', linewidth=2, label='Trend')\n",
            "ax1.axhline(ndvi_df['ndvi'].mean(), color='blue', linestyle='--', label='Mean', alpha=0.7)\n",
            "ax1.fill_between(drought_events.index, 0, 1, alpha=0.2, color='red', transform=ax1.get_xaxis_transform(), label='Drought')\n",
            "ax1.set_xlabel('Date', fontweight='bold')\n",
            "ax1.set_ylabel('NDVI', fontweight='bold')\n",
            "ax1.set_title('MODIS NDVI Time Series (2010-2024) - Sahel Region', fontsize=14, fontweight='bold')\n",
            "ax1.legend(loc='upper left')\n",
            "ax1.grid(alpha=0.3)\n",
            "\n",
            "# 2. Seasonal Decomposition\n",
            "ax2 = fig.add_subplot(gs[1, 0])\n",
            "ax2.plot(seasonal.index, seasonal, color='orange', linewidth=1.5)\n",
            "ax2.set_ylabel('Seasonal', fontweight='bold')\n",
            "ax2.set_title('Seasonal Component', fontweight='bold')\n",
            "ax2.grid(alpha=0.3)\n",
            "\n",
            "ax3 = fig.add_subplot(gs[1, 1])\n",
            "ax3.plot(residual.index, residual, color='gray', linewidth=0.8)\n",
            "ax3.axhline(0, color='black', linestyle='--', alpha=0.5)\n",
            "ax3.set_ylabel('Residual', fontweight='bold')\n",
            "ax3.set_title('Residual Component', fontweight='bold')\n",
            "ax3.grid(alpha=0.3)\n",
            "\n",
            "# 3. NDVI vs Rainfall Scatter\n",
            "ax4 = fig.add_subplot(gs[2, 0])\n",
            "ax4.scatter(merged['rainfall'], merged['ndvi'], alpha=0.6, c=merged.index.year, cmap='viridis', s=30)\n",
            "z = np.polyfit(merged['rainfall'], merged['ndvi'], 1)\n",
            "p = np.poly1d(z)\n",
            "ax4.plot(merged['rainfall'], p(merged['rainfall']), 'r--', linewidth=2, label=f'r={correlation:.3f}')\n",
            "ax4.set_xlabel('Monthly Rainfall (mm)', fontweight='bold')\n",
            "ax4.set_ylabel('NDVI', fontweight='bold')\n",
            "ax4.set_title('NDVI-Rainfall Correlation', fontweight='bold')\n",
            "ax4.legend()\n",
            "ax4.grid(alpha=0.3)\n",
            "\n",
            "# 4. Monthly NDVI Heatmap\n",
            "ax5 = fig.add_subplot(gs[2, 1])\n",
            "pivot_data = ndvi_monthly.copy()\n",
            "pivot_data['year'] = pivot_data.index.year\n",
            "pivot_data['month'] = pivot_data.index.month\n",
            "heatmap_data = pivot_data.pivot(index='year', columns='month', values='ndvi')\n",
            "sns.heatmap(heatmap_data, cmap='RdYlGn', ax=ax5, cbar_kws={'label': 'NDVI'}, vmin=0.2, vmax=0.6)\n",
            "ax5.set_xlabel('Month', fontweight='bold')\n",
            "ax5.set_ylabel('Year', fontweight='bold')\n",
            "ax5.set_title('Monthly NDVI Patterns (2010-2024)', fontweight='bold')\n",
            "\n",
            "# 5. Phenology - Peak NDVI by Year\n",
            "ax6 = fig.add_subplot(gs[3, 0])\n",
            "ax6.bar(pheno_df['Year'], pheno_df['Peak_NDVI'], color='darkgreen', edgecolor='black', alpha=0.7)\n",
            "ax6.set_xlabel('Year', fontweight='bold')\n",
            "ax6.set_ylabel('Peak NDVI', fontweight='bold')\n",
            "ax6.set_title('Annual Peak NDVI', fontweight='bold')\n",
            "ax6.grid(axis='y', alpha=0.3)\n",
            "\n",
            "# 6. Growing Season Length\n",
            "ax7 = fig.add_subplot(gs[3, 1])\n",
            "ax7.plot(pheno_df['Year'], pheno_df['Growing_Season_Length'], 'o-', color='brown', linewidth=2, markersize=8)\n",
            "ax7.set_xlabel('Year', fontweight='bold')\n",
            "ax7.set_ylabel('Days', fontweight='bold')\n",
            "ax7.set_title('Growing Season Length', fontweight='bold')\n",
            "ax7.grid(alpha=0.3)\n",
            "\n",
            "plt.suptitle('Geospatial Time Series Analysis - Vegetation Dynamics', fontsize=16, fontweight='bold', y=0.995)\n",
            "plt.savefig('outputs/vegetation_dynamics_dashboard.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Spatial Mann-Kendall Trend Map\n",
            "print('\\n=== Generating Spatial Trend Map ===')\n",
            "\n",
            "# Calculate pixel-wise trend (simplified - using linear regression)\n",
            "def add_time_band(image):\n",
            "    # Add a time band (fractional year)\n",
            "    date = ee.Date(image.get('system:time_start'))\n",
            "    years = date.difference(ee.Date('2010-01-01'), 'year')\n",
            "    return image.addBands(ee.Image(years).rename('t').float())\n",
            "\n",
            "ndvi_with_time = ndvi_scaled.map(add_time_band)\n",
            "\n",
            "# Linear regression\n",
            "linear_fit = ndvi_with_time.select(['t', 'NDVI']).reduce(ee.Reducer.linearFit())\n",
            "\n",
            "# Extract slope (trend)\n",
            "trend_map = linear_fit.select('scale').clip(sahel_region)\n",
            "\n",
            "# Classify trend significance\n",
            "# Positive: greening, Negative: browning\n",
            "greening = trend_map.gt(0.001)  # Threshold for significant greening\n",
            "browning = trend_map.lt(-0.001)  # Threshold for significant browning\n",
            "\n",
            "# Calculate areas\n",
            "greening_area = greening.multiply(ee.Image.pixelArea()).reduceRegion(\n",
            "    reducer=ee.Reducer.sum(),\n",
            "    geometry=sahel_region,\n",
            "    scale=500,\n",
            "    maxPixels=1e9\n",
            ").get('scale').getInfo() / 1e6\n",
            "\n",
            "browning_area = browning.multiply(ee.Image.pixelArea()).reduceRegion(\n",
            "    reducer=ee.Reducer.sum(),\n",
            "    geometry=sahel_region,\n",
            "    scale=500,\n",
            "    maxPixels=1e9\n",
            ").get('scale').getInfo() / 1e6\n",
            "\n",
            "print(f'Greening area: {greening_area:.2f} km²')\n",
            "print(f'Browning area: {browning_area:.2f} km²')\n",
            "\n",
            "# Interactive Map\n",
            "m = geemap.Map()\n",
            "m.centerObject(sahel_region, 6)\n",
            "\n",
            "trend_vis = {'min': -0.01, 'max': 0.01, 'palette': ['red', 'white', 'green']}\n",
            "m.addLayer(trend_map, trend_vis, 'NDVI Trend (2010-2024)')\n",
            "m.addLayer(sahel_region, {'color': 'black'}, 'Study Area', False)\n",
            "m.add_colorbar(trend_vis, label='NDVI Trend (per year)')\n",
            "\n",
            "m.to_html('outputs/ndvi_trend_map.html')\n",
            "print('✓ Trend map created')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Additional Visualizations\n",
            "fig2 = plt.figure(figsize=(16, 6))\n",
            "gs2 = fig2.add_gridspec(1, 3, wspace=0.3)\n",
            "\n",
            "# 7. Trend Statistics\n",
            "ax8 = fig2.add_subplot(gs2[0])\n",
            "trend_stats = pd.DataFrame({\n",
            "    'Metric': ['Greening Area', 'Browning Area', 'Stable Area'],\n",
            "    'Area (km²)': [greening_area, browning_area, sahel_region.area().getInfo()/1e6 - greening_area - browning_area]\n",
            "})\n",
            "ax8.barh(trend_stats['Metric'], trend_stats['Area (km²)'], color=['green', 'red', 'gray'], edgecolor='black')\n",
            "ax8.set_xlabel('Area (km²)', fontweight='bold')\n",
            "ax8.set_title('Vegetation Trend Classification', fontweight='bold')\n",
            "ax8.grid(axis='x', alpha=0.3)\n",
            "\n",
            "# 8. Phenology DOY Trends\n",
            "ax9 = fig2.add_subplot(gs2[1])\n",
            "ax9.plot(pheno_df['Year'], pheno_df['Peak_DOY'], 'o-', label='Peak', color='green', linewidth=2)\n",
            "ax9.plot(pheno_df['Year'], pheno_df['Greenup_DOY'], 's-', label='Green-up', color='lightgreen', linewidth=2)\n",
            "ax9.plot(pheno_df['Year'], pheno_df['Senescence_DOY'], '^-', label='Senescence', color='brown', linewidth=2)\n",
            "ax9.set_xlabel('Year', fontweight='bold')\n",
            "ax9.set_ylabel('Day of Year', fontweight='bold')\n",
            "ax9.set_title('Phenology Timing Trends', fontweight='bold')\n",
            "ax9.legend()\n",
            "ax9.grid(alpha=0.3)\n",
            "\n",
            "# 9. Summary Statistics Table\n",
            "ax10 = fig2.add_subplot(gs2[2])\n",
            "ax10.axis('off')\n",
            "summary_data = [\n",
            "    ['Mann-Kendall Z', f\"{mk_result['z']:.3f}\"],\n",
            "    ['P-value', f\"{mk_result['p']:.4f}\"],\n",
            "    ['Sen\\'s Slope', f\"{sens*365:.4f}/yr\"],\n",
            "    ['NDVI-Rain Corr', f'{correlation:.3f}'],\n",
            "    ['Drought Events', f'{len(drought_events)}'],\n",
            "    ['Greening Area', f'{greening_area:.0f} km²'],\n",
            "    ['Browning Area', f'{browning_area:.0f} km²']\n",
            "]\n",
            "table = ax10.table(cellText=summary_data, colLabels=['Metric', 'Value'],\n",
            "                  cellLoc='left', loc='center', bbox=[0, 0, 1, 1])\n",
            "table.auto_set_font_size(False)\n",
            "table.set_fontsize(10)\n",
            "table.scale(1, 2)\n",
            "ax10.set_title('Summary Statistics', fontweight='bold', pad=20)\n",
            "\n",
            "plt.suptitle('Trend Analysis Summary', fontsize=14, fontweight='bold')\n",
            "plt.savefig('outputs/trend_analysis_summary.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Display Interactive Map\n",
            "print('\\n=== Interactive Trend Map ===')\n",
            "display(m)"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Future Trend Forecasting (Linear Extrapolation)\n",
            "print('\\n=== Future Trend Forecasting ===')\n",
            "\n",
            "# Create future dates\n",
            "last_date = ndvi_df.index.max()\n",
            "future_dates = pd.date_range(start=last_date, periods=365*5, freq='D')\n",
            "future_days = (future_dates - ndvi_df.index.min()).days\n",
            "\n",
            "# Calculate trend line\n",
            "intercept = ndvi_df['ndvi'].mean() - sens * (ndvi_df.index - ndvi_df.index.min()).days.mean()\n",
            "future_ndvi = intercept + sens * future_days\n",
            "\n",
            "# Plot forecast\n",
            "plt.figure(figsize=(12, 6))\n",
            "plt.plot(ndvi_df.index, ndvi_df['ndvi'], label='Historical NDVI', alpha=0.5, color='green')\n",
            "plt.plot(future_dates, future_ndvi, label='Projected Trend (5 Years)', color='red', linestyle='--', linewidth=2)\n",
            "\n",
            "# Add confidence intervals (simplified)\n",
            "std_dev = ndvi_df['ndvi'].std()\n",
            "plt.fill_between(future_dates, future_ndvi - std_dev, future_ndvi + std_dev, color='red', alpha=0.1, label='1 Std Dev')\n",
            "\n",
            "plt.xlabel('Date', fontweight='bold')\n",
            "plt.ylabel('NDVI', fontweight='bold')\n",
            "plt.title('Vegetation Trend Forecast (2024-2029)', fontweight='bold')\n",
            "plt.legend()\n",
            "plt.grid(alpha=0.3)\n",
            "plt.savefig('outputs/vegetation_trend_forecast.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()\n",
            "\n",
            "print(f'Projected NDVI in 5 years: {future_ndvi[-1]:.3f}')"
        ]},

        {"cell_type": "code", "metadata": {}, "source": [
            "# Generate Dynamic Summary Report\n",
            "from IPython.display import Markdown, display\n",
            "\n",
            "summary_md = f\"\"\"\n",
            "## 🎯 Key Findings & Recommendations\n\n",
            "### Trend Analysis Summary\n\n",
            "1. **Overall Trend**: Mann-Kendall test shows {mk_result['trend'].lower()} (Z={mk_result['z']:.3f}).\n",
            "2. **Magnitude**: Sen's slope indicates change of {sens*365:.4f} NDVI/year.\n",
            "3. **Drivers**: Rainfall correlation is {correlation:.3f}, confirming it as a key driver.\n",
            "4. **Droughts**: {len(drought_events)} drought events detected in the study period.\n\n",
            "### Spatial Patterns\n",
            "- **Greening**: {greening_area:.0f} km²\n",
            "- **Browning**: {browning_area:.0f} km²\n\n",
            "### Future Outlook\n",
            "- **Forecast**: Projected NDVI in 5 years is {future_ndvi[-1]:.3f}, following the current {mk_result['trend'].lower()} trend.\n\n",
            "### Recommendations\n",
            "1. **Early Warning**: Monitor NDVI anomalies < -1.5 SD.\n",
            "2. **Intervention**: Target browning areas ({browning_area:.0f} km²) for restoration.\n",
            "3. **Research**: Investigate non-rainfall drivers in browning zones.\n",
            "\"\"\"\n",
            "display(Markdown(summary_md))"
        ]}
    ]
    
    return json.dumps(create_notebook(cells), indent=1)

if __name__ == "__main__":
    print("Generating Geospatial Time Series Analysis notebook...")
    nb_json = generate_geospatial_timeseries_notebook()
    print(f"✓ Generated notebook with {len(json.loads(nb_json)['cells'])} cells")
