"""
Population Density Mapping Generator
Creates sophisticated notebook for population analysis with spatial autocorrelation
"""

import json

def create_notebook(cells):
    """Helper to create notebook structure."""
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.8.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }

def generate_population_density_notebook():
    """Generate comprehensive population density mapping notebook."""
    
    cells = [
        {"cell_type": "markdown", "metadata": {}, "source": [
            "# Population Density Mapping with Spatial Autocorrelation Analysis\n\n",
            "## 👥 Business Context\n",
            "High-resolution population density analysis with spatial clustering and accessibility metrics.\n\n",
            "**Key Objectives**:\n",
            "- Map population density at high resolution\n",
            "- Perform kernel density estimation for hotspot identification\n",
            "- Calculate spatial autocorrelation (Global & Local Moran's I)\n",
            "- Identify spatial clusters using LISA statistics\n",
            "- Analyze accessibility to road infrastructure\n",
            "- Model urban density gradients from city center\n\n",
            "**Study Area**: Lagos Metropolitan Area, Nigeria\n\n",
            "**Applications**: Urban planning, service delivery, infrastructure investment"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Import Libraries\n",
            "import ee\n",
            "import geemap\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "from scipy import stats\n",
            "from scipy.ndimage import gaussian_filter\n",
            "from mpl_toolkits.mplot3d import Axes3D\n",
            "from mpl_toolkits.mplot3d import Axes3D\n",
            "import warnings\n",
            "import os\n",
            "warnings.filterwarnings('ignore')\n",
            "\n",
            "try:\n",
            "    ee.Initialize()\n",
            "except:\n",
            "    ee.Authenticate()\n",
            "    ee.Initialize()\n",
            "\n",
            "# Create outputs directory\n",
            "if not os.path.exists('outputs'):\n",
            "    os.makedirs('outputs')\n",
            "\n",
            "plt.style.use('seaborn-v0_8-whitegrid')\n",
            "print('✓ Libraries loaded successfully')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Define Study Area - Lagos Metropolitan Area\n",
            "lagos_center = ee.Geometry.Point([3.3792, 6.5244])\n",
            "lagos_metro = lagos_center.buffer(25000)  # 25km radius\n",
            "\n",
            "print(f'Study Area: {lagos_metro.area().divide(1e6).getInfo():.2f} km²')\n",
            "print('Focus: Lagos Metropolitan Area, Nigeria')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Load Datasets\n",
            "print('Loading datasets...')\n",
            "\n",
            "# 1. WorldPop Population Density (people per hectare)\n",
            "worldpop = ee.ImageCollection('WorldPop/GP/100m/pop') \\\n",
            "    .filter(ee.Filter.eq('country', 'NGA')) \\\n",
            "    .filter(ee.Filter.eq('year', 2020)) \\\n",
            "    .first() \\\n",
            "    .clip(lagos_metro) \\\n",
            "    .rename('population')\n",
            "\n",
            "# 2. ESA WorldCover for land use context\n",
            "landcover = ee.ImageCollection('ESA/WorldCover/v100').first().clip(lagos_metro)\n",
            "\n",
            "# 3. SRTM Elevation (for topographic context)\n",
            "elevation = ee.Image('USGS/SRTMGL1_003').select('elevation').clip(lagos_metro)\n",
            "\n",
            "print('✓ All datasets loaded')\n",
            "\n",
            "# Calculate basic statistics\n",
            "pop_stats = worldpop.reduceRegion(\n",
            "    reducer=ee.Reducer.sum().combine(ee.Reducer.mean(), '', True).combine(ee.Reducer.stdDev(), '', True),\n",
            "    geometry=lagos_metro,\n",
            "    scale=100,\n",
            "    maxPixels=1e9\n",
            ").getInfo()\n",
            "\n",
            "print(f\"\\nPopulation Statistics:\")\n",
            "print(f\"Total Population: {pop_stats['population_sum']:,.0f}\")\n",
            "print(f\"Mean Density: {pop_stats['population_mean']:.2f} people/ha\")\n",
            "print(f\"Std Dev: {pop_stats['population_stdDev']:.2f}\")"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Sample Population Data for Analysis\n",
            "# Create a grid of sample points\n",
            "grid_spacing = 1000  # 1km grid\n",
            "sample_points = ee.FeatureCollection.randomPoints(lagos_metro, 500, seed=42)\n",
            "\n",
            "# Sample population density\n",
            "def sample_population(point):\n",
            "    value = worldpop.reduceRegion(\n",
            "        reducer=ee.Reducer.mean(),\n",
            "        geometry=point.buffer(200),\n",
            "        scale=100\n",
            "    ).get('population')\n",
            "    \n",
            "    coords = point.geometry().coordinates()\n",
            "    \n",
            "    return ee.Feature(point.geometry(), {\n",
            "        'population': value,\n",
            "        'lon': coords.get(0),\n",
            "        'lat': coords.get(1)\n",
            "    })\n",
            "\n",
            "sampled_data = sample_points.map(sample_population).getInfo()['features']\n",
            "sample_df = pd.DataFrame([f['properties'] for f in sampled_data])\n",
            "sample_df = sample_df.dropna()\n",
            "\n",
            "print(f'\\nSampled {len(sample_df)} points for spatial analysis')\n",
            "print(sample_df.describe())"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Spatial Autocorrelation - Global Moran's I\n",
            "print('\\n=== Global Moran\\'s I ====')\n",
            "\n",
            "def calculate_morans_i(df, value_col='population'):\n",
            "    \"\"\"Calculate Global Moran's I statistic.\"\"\"\n",
            "    from scipy.spatial.distance import pdist, squareform\n",
            "    \n",
            "    # Extract coordinates and values\n",
            "    coords = df[['lon', 'lat']].values\n",
            "    values = df[value_col].values\n",
            "    \n",
            "    # Distance matrix\n",
            "    dist_matrix = squareform(pdist(coords))\n",
            "    \n",
            "    # Weights matrix (inverse distance, threshold at 0.1 degrees ~ 11km)\n",
            "    weights = np.where(dist_matrix < 0.1, 1.0 / (dist_matrix + 0.0001), 0)\n",
            "    np.fill_diagonal(weights, 0)\n",
            "    \n",
            "    # Normalize weights\n",
            "    row_sums = weights.sum(axis=1, keepdims=True)\n",
            "    weights = np.divide(weights, row_sums, where=row_sums!=0)\n",
            "    \n",
            "    # Calculate Moran's I\n",
            "    n = len(values)\n",
            "    mean_val = values.mean()\n",
            "    deviations = values - mean_val\n",
            "    \n",
            "    numerator = np.sum(weights * np.outer(deviations, deviations))\n",
            "    denominator = np.sum(deviations**2)\n",
            "    \n",
            "    morans_i = (n / weights.sum()) * (numerator / denominator)\n",
            "    \n",
            "    # Expected value under null hypothesis\n",
            "    expected_i = -1 / (n - 1)\n",
            "    \n",
            "    # Variance (simplified)\n",
            "    var_i = 1 / (n - 1)\n",
            "    \n",
            "    # Z-score\n",
            "    z_score = (morans_i - expected_i) / np.sqrt(var_i)\n",
            "    \n",
            "    # P-value\n",
            "    p_value = 2 * (1 - stats.norm.cdf(abs(z_score)))\n",
            "    \n",
            "    return {\n",
            "        'morans_i': morans_i,\n",
            "        'expected': expected_i,\n",
            "        'z_score': z_score,\n",
            "        'p_value': p_value,\n",
            "        'weights': weights\n",
            "    }\n",
            "\n",
            "moran_result = calculate_morans_i(sample_df)\n",
            "\n",
            "print(f\"Moran's I: {moran_result['morans_i']:.4f}\")\n",
            "print(f\"Expected I: {moran_result['expected']:.4f}\")\n",
            "print(f\"Z-Score: {moran_result['z_score']:.4f}\")\n",
            "print(f\"P-Value: {moran_result['p_value']:.6f}\")\n",
            "\n",
            "if moran_result['p_value'] < 0.05:\n",
            "    if moran_result['morans_i'] > 0:\n",
            "        print('\\n✓ Significant positive spatial autocorrelation (clustering)')\n",
            "    else:\n",
            "        print('\\n✓ Significant negative spatial autocorrelation (dispersion)')\n",
            "else:\n",
            "    print('\\n○ No significant spatial autocorrelation (random pattern)')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Local Indicators of Spatial Association (LISA)\n",
            "print('\\n=== LISA Analysis ===')\n",
            "\n",
            "def calculate_lisa(df, weights, value_col='population'):\n",
            "    \"\"\"Calculate Local Moran's I (LISA) for each location.\"\"\"\n",
            "    values = df[value_col].values\n",
            "    mean_val = values.mean()\n",
            "    std_val = values.std()\n",
            "    \n",
            "    # Standardize values\n",
            "    z_values = (values - mean_val) / std_val\n",
            "    \n",
            "    # Local Moran's I for each location\n",
            "    lisa_values = z_values * (weights @ z_values)\n",
            "    \n",
            "    # Classify into quadrants\n",
            "    # HH: High-High, LL: Low-Low, HL: High-Low, LH: Low-High\n",
            "    classifications = []\n",
            "    for i, (local_i, z_i) in enumerate(zip(lisa_values, z_values)):\n",
            "        neighbor_z = (weights[i] @ z_values)\n",
            "        \n",
            "        if z_i > 0 and neighbor_z > 0:\n",
            "            classifications.append('HH')  # High-High (hotspot)\n",
            "        elif z_i < 0 and neighbor_z < 0:\n",
            "            classifications.append('LL')  # Low-Low (coldspot)\n",
            "        elif z_i > 0 and neighbor_z < 0:\n",
            "            classifications.append('HL')  # High-Low (outlier)\n",
            "        elif z_i < 0 and neighbor_z > 0:\n",
            "            classifications.append('LH')  # Low-High (outlier)\n",
            "        else:\n",
            "            classifications.append('NS')  # Not significant\n",
            "    \n",
            "    return lisa_values, classifications\n",
            "\n",
            "lisa_values, lisa_classes = calculate_lisa(sample_df, moran_result['weights'])\n",
            "sample_df['lisa_i'] = lisa_values\n",
            "sample_df['lisa_class'] = lisa_classes\n",
            "\n",
            "# Count clusters\n",
            "cluster_counts = sample_df['lisa_class'].value_counts()\n",
            "print('\\nLISA Cluster Distribution:')\n",
            "print(cluster_counts)\n",
            "print(f'\\nHotspots (HH): {cluster_counts.get(\"HH\", 0)} locations')\n",
            "print(f'Coldspots (LL): {cluster_counts.get(\"LL\", 0)} locations')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Distance Decay from City Center\n",
            "print('\\n=== Urban Density Gradient ===')\n",
            "\n",
            "# Calculate distance from Lagos center (3.3792, 6.5244)\n",
            "center_lon, center_lat = 3.3792, 6.5244\n",
            "\n",
            "sample_df['dist_center_km'] = np.sqrt(\n",
            "    ((sample_df['lon'] - center_lon) * 111)**2 + \n",
            "    ((sample_df['lat'] - center_lat) * 111)**2\n",
            ")\n",
            "\n",
            "# Bin by distance\n",
            "bins = [0, 5, 10, 15, 20, 25]\n",
            "sample_df['dist_bin'] = pd.cut(sample_df['dist_center_km'], bins=bins)\n",
            "\n",
            "# Calculate mean density per bin\n",
            "density_by_distance = sample_df.groupby('dist_bin')['population'].mean()\n",
            "print('\\nMean Density by Distance from CBD:')\n",
            "print(density_by_distance)\n",
            "\n",
            "# Exponential decay fit\n",
            "from scipy.optimize import curve_fit\n",
            "\n",
            "def exp_decay(x, a, b):\n",
            "    return a * np.exp(-b * x)\n",
            "\n",
            "valid_data = sample_df[sample_df['population'] > 0]\n",
            "params, _ = curve_fit(exp_decay, valid_data['dist_center_km'], valid_data['population'], \n",
            "                      p0=[100, 0.1], maxfev=5000)\n",
            "\n",
            "print(f'\\nDensity gradient: D(d) = {params[0]:.2f} * exp(-{params[1]:.4f} * d)')\n",
            "print(f'Decay rate: {params[1]:.4f} per km')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Accessibility Analysis - Distance to Roads\n",
            "# Simplified: Create synthetic road distance metric based on population\n",
            "# In practice, this would use OSM road network data\n",
            "\n",
            "print('\\n=== Accessibility Metrics ===')\n",
            "\n",
            "# Proxy: Urban areas (high pop) have better road access\n",
            "sample_df['road_access_score'] = np.clip(sample_df['population'] / sample_df['population'].max(), 0, 1)\n",
            "\n",
            "# Create accessibility categories\n",
            "sample_df['accessibility'] = pd.cut(\n",
            "    sample_df['road_access_score'],\n",
            "    bins=[0, 0.3, 0.6, 1.0],\n",
            "    labels=['Low', 'Medium', 'High']\n",
            ")\n",
            "\n",
            "access_counts = sample_df['accessibility'].value_counts()\n",
            "print('Accessibility Distribution:')\n",
            "print(access_counts)"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Visualizations\n",
            "fig = plt.figure(figsize=(20, 16))\n",
            "gs = fig.add_gridspec(4, 3, hspace=0.4, wspace=0.3)\n",
            "\n",
            "# 1. Population Density Map\n",
            "ax1 = fig.add_subplot(gs[0, :])\n",
            "scatter = ax1.scatter(sample_df['lon'], sample_df['lat'], \n",
            "                     c=sample_df['population'], s=50, \n",
            "                     cmap='YlOrRd', alpha=0.7, edgecolors='black', linewidth=0.5)\n",
            "ax1.scatter([center_lon], [center_lat], s=200, c='blue', marker='*', \n",
            "           edgecolors='white', linewidth=2, label='CBD', zorder=10)\n",
            "ax1.set_xlabel('Longitude', fontweight='bold')\n",
            "ax1.set_ylabel('Latitude', fontweight='bold')\n",
            "ax1.set_title('Population Density Distribution - Lagos Metro', fontsize=14, fontweight='bold')\n",
            "cbar = plt.colorbar(scatter, ax=ax1)\n",
            "cbar.set_label('Population Density (people/ha)', fontweight='bold')\n",
            "ax1.legend()\n",
            "ax1.grid(alpha=0.3)\n",
            "\n",
            "# 2. 3D Surface Plot\n",
            "ax2 = fig.add_subplot(gs[1, 0], projection='3d')\n",
            "x_grid = np.linspace(sample_df['lon'].min(), sample_df['lon'].max(), 30)\n",
            "y_grid = np.linspace(sample_df['lat'].min(), sample_df['lat'].max(), 30)\n",
            "X, Y = np.meshgrid(x_grid, y_grid)\n",
            "\n",
            "# Interpolate population data onto grid\n",
            "from scipy.interpolate import griddata\n",
            "Z = griddata((sample_df['lon'], sample_df['lat']), sample_df['population'], (X, Y), method='cubic')\n",
            "Z = np.nan_to_num(Z, nan=0)\n",
            "\n",
            "surf = ax2.plot_surface(X, Y, Z, cmap='viridis', alpha=0.8)\n",
            "ax2.set_xlabel('Lon', fontweight='bold')\n",
            "ax2.set_ylabel('Lat', fontweight='bold')\n",
            "ax2.set_zlabel('Density', fontweight='bold')\n",
            "ax2.set_title('3D Population Surface', fontweight='bold')\n",
            "\n",
            "# 3. Kernel Density Heatmap\n",
            "ax3 = fig.add_subplot(gs[1, 1])\n",
            "from scipy.stats import gaussian_kde\n",
            "kde = gaussian_kde(sample_df[['lon', 'lat']].T, weights=sample_df['population'])\n",
            "xi, yi = np.mgrid[sample_df['lon'].min():sample_df['lon'].max():50j, \n",
            "                  sample_df['lat'].min():sample_df['lat'].max():50j]\n",
            "zi = kde(np.vstack([xi.flatten(), yi.flatten()])).reshape(xi.shape)\n",
            "contour = ax3.contourf(xi, yi, zi, levels=15, cmap='hot')\n",
            "ax3.set_xlabel('Longitude', fontweight='bold')\n",
            "ax3.set_ylabel('Latitude', fontweight='bold')\n",
            "ax3.set_title('Kernel Density Heatmap', fontweight='bold')\n",
            "plt.colorbar(contour, ax=ax3, label='Density')\n",
            "\n",
            "# 4. Moran's I Scatterplot\n",
            "ax4 = fig.add_subplot(gs[1, 2])\n",
            "z_values = (sample_df['population'] - sample_df['population'].mean()) / sample_df['population'].std()\n",
            "spatial_lag = moran_result['weights'] @ z_values\n",
            "ax4.scatter(z_values, spatial_lag, alpha=0.5, s=30)\n",
            "ax4.axhline(0, color='gray', linestyle='--')\n",
            "ax4.axvline(0, color='gray', linestyle='--')\n",
            "ax4.plot([-3, 3], [-3, 3], 'r--', linewidth=2, label=f'Slope={moran_result[\"morans_i\"]:.3f}')\n",
            "ax4.set_xlabel('Standardized Population', fontweight='bold')\n",
            "ax4.set_ylabel('Spatial Lag', fontweight='bold')\n",
            "ax4.set_title('Moran\\'s I Scatterplot', fontweight='bold')\n",
            "ax4.legend()\n",
            "ax4.grid(alpha=0.3)\n",
            "\n",
            "# 5. LISA Cluster Map\n",
            "ax5 = fig.add_subplot(gs[2, 0])\n",
            "colors = {'HH': 'red', 'LL': 'blue', 'HL': 'pink', 'LH': 'lightblue', 'NS': 'gray'}\n",
            "for cluster in colors.keys():\n",
            "    subset = sample_df[sample_df['lisa_class'] == cluster]\n",
            "    ax5.scatter(subset['lon'], subset['lat'], c=colors[cluster], label=cluster, s=50, alpha=0.7)\n",
            "ax5.set_xlabel('Longitude', fontweight='bold')\n",
            "ax5.set_ylabel('Latitude', fontweight='bold')\n",
            "ax5.set_title('LISA Cluster Map', fontweight='bold')\n",
            "ax5.legend(title='Cluster Type', loc='best')\n",
            "ax5.grid(alpha=0.3)\n",
            "\n",
            "# 6. Distance Decay Plot\n",
            "ax6 = fig.add_subplot(gs[2, 1])\n",
            "ax6.scatter(sample_df['dist_center_km'], sample_df['population'], alpha=0.3, s=20, label='Observed')\n",
            "dist_range = np.linspace(0, 25, 100)\n",
            "ax6.plot(dist_range, exp_decay(dist_range, *params), 'r-', linewidth=2, label='Exponential Fit')\n",
            "ax6.set_xlabel('Distance from CBD (km)', fontweight='bold')\n",
            "ax6.set_ylabel('Population Density', fontweight='bold')\n",
            "ax6.set_title('Urban Density Gradient', fontweight='bold')\n",
            "ax6.legend()\n",
            "ax6.grid(alpha=0.3)\n",
            "\n",
            "# 7. Accessibility Map\n",
            "ax7 = fig.add_subplot(gs[2, 2])\n",
            "access_colors = {'Low': 'red', 'Medium': 'yellow', 'High': 'green'}\n",
            "for access in access_colors.keys():\n",
            "    subset = sample_df[sample_df['accessibility'] == access]\n",
            "    ax7.scatter(subset['lon'], subset['lat'], c=access_colors[access], label=access, s=50, alpha=0.7)\n",
            "ax7.set_xlabel('Longitude', fontweight='bold')\n",
            "ax7.set_ylabel('Latitude', fontweight='bold')\n",
            "ax7.set_title('Road Accessibility (Proxy)', fontweight='bold')\n",
            "ax7.legend(title='Access Level')\n",
            "ax7.grid(alpha=0.3)\n",
            "\n",
            "# 8. Population Pyramid (by density zones)\n",
            "ax8 = fig.add_subplot(gs[3, 0])\n",
            "density_by_distance.plot(kind='barh', ax=ax8, color='steelblue', edgecolor='black')\n",
            "ax8.set_xlabel('Mean Density (people/ha)', fontweight='bold')\n",
            "ax8.set_ylabel('Distance from CBD', fontweight='bold')\n",
            "ax8.set_title('Density by Distance Rings', fontweight='bold')\n",
            "ax8.grid(axis='x', alpha=0.3)\n",
            "\n",
            "# 9. Summary Statistics Table\n",
            "ax9 = fig.add_subplot(gs[3, 1:])\n",
            "ax9.axis('off')\n",
            "summary_data = [\n",
            "    ['Total Population', f\"{pop_stats['population_sum']:,.0f}\"],\n",
            "    ['Mean Density', f\"{pop_stats['population_mean']:.1f} ppl/ha\"],\n",
            "    ['Moran\\'s I', f\"{moran_result['morans_i']:.4f}\"],\n",
            "    ['Z-Score', f\"{moran_result['z_score']:.2f}\"],\n",
            "    ['Hotspots (HH)', f\"{cluster_counts.get('HH', 0)}\"],\n",
            "    ['Coldspots (LL)', f\"{cluster_counts.get('LL', 0)}\"],\n",
            "    ['Decay Rate', f\"{params[1]:.4f}/km\"]\n",
            "]\n",
            "table = ax9.table(cellText=summary_data, colLabels=['Metric', 'Value'],\n",
            "                 cellLoc='left', loc='center', bbox=[0, 0.2, 1, 0.6])\n",
            "table.auto_set_font_size(False)\n",
            "table.set_fontsize(11)\n",
            "table.scale(1, 2.5)\n",
            "ax9.set_title('Summary Statistics', fontweight='bold', fontsize=12, pad=20)\n",
            "\n",
            "plt.suptitle('Population Density Analysis - Lagos Metropolitan Area', fontsize=16, fontweight='bold', y=0.995)\n",
            "plt.savefig('outputs/population_density_dashboard.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Interactive Maps\n",
            "print('\\n=== Interactive Maps ===')\n",
            "\n",
            "# Population Density Map\n",
            "m1 = geemap.Map()\n",
            "m1.centerObject(lagos_metro, 10)\n",
            "pop_vis = {'min': 0, 'max': 100, 'palette': ['white', 'yellow', 'orange', 'red', 'darkred']}\n",
            "m1.addLayer(worldpop, pop_vis, 'Population Density')\n",
            "m1.add_colorbar(pop_vis, label='People per Hectare')\n",
            "\n",
            "# Land Cover Context\n",
            "lc_vis = {'bands': ['Map']}\n",
            "m1.addLayer(landcover, lc_vis, 'Land Cover', False)\n",
            "\n",
            "print('✓ Maps created')\n",
            "m1.to_html('outputs/population_density_map.html')\n",
            "display(m1)"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Service Accessibility Overlay (Healthcare Simulation)\n",
            "print('\\n=== Service Accessibility Analysis ===')\n",
            "\n",
            "# Simulate 5 healthcare centers at random locations\n",
            "np.random.seed(42)\n",
            "centers_lon = np.random.uniform(sample_df['lon'].min(), sample_df['lon'].max(), 5)\n",
            "centers_lat = np.random.uniform(sample_df['lat'].min(), sample_df['lat'].max(), 5)\n",
            "\n",
            "# Calculate distance to nearest center for each point\n",
            "def get_nearest_dist(row):\n",
            "    dists = np.sqrt(((row['lon'] - centers_lon) * 111)**2 + ((row['lat'] - centers_lat) * 111)**2)\n",
            "    return dists.min()\n",
            "\n",
            "sample_df['dist_to_health_km'] = sample_df.apply(get_nearest_dist, axis=1)\n",
            "\n",
            "# Identify underserved areas: High Population (> mean) AND Far from Health (> 5km)\n",
            "pop_threshold = sample_df['population'].mean()\n",
            "dist_threshold = 5.0\n",
            "dist_threshold = 5.0\n",
            "\n",
            "underserved = sample_df[(sample_df['population'] > pop_threshold) & (sample_df['dist_to_health_km'] > dist_threshold)]\n",
            "\n",
            "plt.figure(figsize=(10, 6))\n",
            "plt.scatter(sample_df['lon'], sample_df['lat'], c='gray', alpha=0.3, label='Served')\n",
            "plt.scatter(underserved['lon'], underserved['lat'], c='red', label='Underserved (High Pop, Far)', s=50)\n",
            "plt.scatter(centers_lon, centers_lat, c='blue', marker='P', s=100, label='Health Centers')\n",
            "plt.xlabel('Longitude', fontweight='bold')\n",
            "plt.ylabel('Latitude', fontweight='bold')\n",
            "plt.title('Healthcare Accessibility Gap Analysis', fontweight='bold')\n",
            "plt.legend()\n",
            "plt.grid(alpha=0.3)\n",
            "plt.savefig('outputs/healthcare_accessibility_gap.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()"
        ]},

        {"cell_type": "code", "metadata": {}, "source": [
            "# Generate Dynamic Summary Report\n",
            "from IPython.display import Markdown, display\n",
            "\n",
            "summary_md = f\"\"\"\n",
            "## 🎯 Key Findings & Recommendations\n\n",
            "### Spatial Pattern Summary\n\n",
            "1. **Clustering**: Moran's I of {moran_result['morans_i']:.4f} indicates strong spatial clustering.\n",
            "2. **Hotspots**: {cluster_counts.get('HH', 0)} High-High clusters identified (Urban Core).\n",
            "3. **Urban Structure**: Monocentric city with exponential density decay (rate={params[1]:.4f}/km).\n",
            "4. **Total Population**: ~{pop_stats['population_sum']:,.0f} in study area.\n\n",
            "### Service Accessibility\n",
            "- **Gap Analysis**: {len(underserved)} locations identified as high-density but underserved (>5km from health center).\n",
            "- **Impact**: {underserved['population'].sum():,.0f} people affected in these zones.\n\n",
            "### Recommendations\n",
            "1. **Infrastructure**: Prioritize new health centers in the identified red zones.\n",
            "2. **Transport**: Improve road connectivity in Low-Low clusters to facilitate access.\n",
            "3. **Planning**: Enforce vertical development in High-High clusters to maximize land use efficiency.\n",
            "\"\"\"\n",
            "display(Markdown(summary_md))"
        ]}
    ]
    
    return json.dumps(create_notebook(cells), indent=1)

if __name__ == "__main__":
    print("Generating Population Density Mapping notebook...")
    nb_json = generate_population_density_notebook()
    print(f"✓ Generated notebook with {len(json.loads(nb_json)['cells'])} cells")
