"""
Remaining Use Case Generators (4/7): Retail, Service Area, Clustering, Transportation
This file contains the final 4 generators to complete the suite of 7 GISuse cases.
"""

import json

def create_notebook(cells):
    """Helper to create notebook structure."""
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.8.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }

# ==============================================================================
# GENERATOR 4: RETAIL SITE SELECTION
# ==============================================================================

def generate_retail_site_selection_notebook():
    """Generate retail site selection notebook with gravity model."""
    
    cells = [
        {"cell_type": "markdown", "metadata": {}, "source": [
            "# Retail Site Selection - Gravity Model Analysis\n\n",
            "## 🏪 Business Context\n",
            "Optimal location selection for retail facilities using multi-criteria scoring and gravity models.\n\n",
            "**Key Objectives**:\n",
            "- Apply Huff gravity model for market area delineation\n",
            "- Implement Reilly's law of retail gravitation\n",
            "- Multi-criteria site scoring (population, accessibility, competition)\n",
            "- Generate Thiessen polygons for territory analysis\n",
            "- Analyze competitive overlap and market potential\n\n",
            "**Study Area**: Accra, Ghana\n\n",
            "**Applications**: Retail expansion, real estate investment, market analysis"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Import Libraries\n",
            "import ee\n",
            "import geemap\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "from scipy.spatial import Voronoi, voronoi_plot_2d\n",
            "from scipy.spatial.distance import cdist\n",
            "from scipy.spatial.distance import cdist\n",
            "import warnings\n",
            "import os\n",
            "warnings.filterwarnings('ignore')\n",
            "\n",
            "try:\n",
            "    ee.Initialize()\n",
            "except:\n",
            "    ee.Authenticate()\n",
            "    ee.Initialize()\n",
            "\n",
            "# Create outputs directory\n",
            "if not os.path.exists('outputs'):\n",
            "    os.makedirs('outputs')\n",
            "\n",
            "plt.style.use('seaborn-v0_8-whitegrid')\n",
            "print('✓ Libraries loaded successfully')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Define Study Area - Accra, Ghana\n",
            "accra_center = ee.Geometry.Point([-0.1870, 5.6037])\n",
            "accra_metro = accra_center.buffer(20000)\n",
            "\n",
            "print(f'Study Area: {accra_metro.area().divide(1e6).getInfo():.2f} km²')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Load Data\n",
            "# Population\n",
            "worldpop = ee.ImageCollection('WorldPop/GP/100m/pop') \\\n",
            "    .filter(ee.Filter.eq('country', 'GHA')) \\\n",
            "    .filter(ee.Filter.eq('year', 2020)) \\\n",
            "    .first().clip(accra_metro)\n",
            "\n",
            "# Nighttime lights (income proxy)\n",
            "viirs = ee.ImageCollection('NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG') \\\n",
            "    .filterDate('2020-01-01', '2020-12-31') \\\n",
            "    .select('avg_rad') \\\n",
            "    .median().clip(accra_metro)\n",
            "\n",
            "print('✓ Datasets loaded')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Define Existing Competitors (synthetic)\n",
            "competitors = pd.DataFrame({\n",
            "    'name': ['Store_A', 'Store_B', 'Store_C', 'Store_D'],\n",
            "    'lon': [-0.20, -0.17, -0.22, -0.15],\n",
            "    'lat': [5.61, 5.60, 5.58, 5.62],\n",
            "    'size': [5000, 3000, 4000, 3500]  # sq meters\n",
            "})\n",
            "\n",
            "# Candidate Sites (to evaluate)\n",
            "candidates = pd.DataFrame({\n",
            "    'site_id': ['Site_1', 'Site_2', 'Site_3', 'Site_4', 'Site_5'],\n",
            "    'lon': [-0.19, -0.16, -0.21, -0.18, -0.14],\n",
            "    'lat': [5.59, 5.61, 5.60, 5.63, 5.58]\n",
            "})\n",
            "\n",
            "print(f'Competitors: {len(competitors)}')\n",
            "print(f'Candidate sites: {len(candidates)}')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Multi-Criteria Scoring\n",
            "# Extract metrics for each candidate\n",
            "\n",
            "def evaluate_site(lon, lat, buffer_m=1000):\n",
            "    point = ee.Geometry.Point([lon, lat]).buffer(buffer_m)\n",
            "    \n",
            "    # Population within 1km\n",
            "    pop = worldpop.reduceRegion(\n",
            "        reducer=ee.Reducer.sum(),\n",
            "        geometry=point,\n",
            "        scale=100,\n",
            "        maxPixels=1e9\n",
            "    ).get('population').getInfo()\n",
            "    \n",
            "    # Income proxy (nighttime lights)\n",
            "    income = viirs.reduceRegion(\n",
            "        reducer=ee.Reducer.mean(),\n",
            "        geometry=point,\n",
            "        scale=500,\n",
            "        maxPixels=1e9\n",
            "    ).get('avg_rad').getInfo()\n",
            "    \n",
            "    # Distance to nearest competitor\n",
            "    comp_dists = np.sqrt(\n",
            "        (competitors['lon'] - lon)**2 + (competitors['lat'] - lat)**2\n",
            "    ) * 111  # Convert to km\n",
            "    min_comp_dist = comp_dists.min()\n",
            "    \n",
            "    return {\n",
            "        'population_1km': pop if pop else 0,\n",
            "        'income_proxy': income if income else 0,\n",
            "        'min_competitor_dist_km': min_comp_dist\n",
            "    }\n",
            "\n",
            "print('Evaluating candidate sites...')\n",
            "candidate_scores = []\n",
            "for _, row in candidates.iterrows():\n",
            "    scores = evaluate_site(row['lon'], row['lat'])\n",
            "    candidate_scores.append(scores)\n",
            "\n",
            "scores_df = pd.concat([candidates, pd.DataFrame(candidate_scores)], axis=1)\n",
            "print('\\nCandidate Site Scores:')\n",
            "display(scores_df)"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Weighted Scoring\n",
            "# Normalize and apply weights\n",
            "\n",
            "def normalize(series):\n",
            "    return (series - series.min()) / (series.max() - series.min())\n",
            "\n",
            "scores_df['pop_score'] = normalize(scores_df['population_1km'])\n",
            "scores_df['income_score'] = normalize(scores_df['income_proxy'])\n",
            "scores_df['competition_score'] = normalize(scores_df['min_competitor_dist_km'])  # Higher is better\n",
            "\n",
            "# Weights\n",
            "weights = {'population': 0.4, 'income': 0.35, 'competition': 0.25}\n",
            "\n",
            "scores_df['total_score'] = (\n",
            "    scores_df['pop_score'] * weights['population'] +\n",
            "    scores_df['income_score'] * weights['income'] +\n",
            "    scores_df['competition_score'] * weights['competition']\n",
            ")\n",
            "\n",
            "scores_df = scores_df.sort_values('total_score', ascending=False)\n",
            "print('\\nRanked Candidates:')\n",
            "display(scores_df[['site_id', 'total_score', 'pop_score', 'income_score', 'competition_score']])"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Huff Gravity Model\n",
            "# Probability of patronage based on attraction / distance\n",
            "\n",
            "def huff_model(customer_coords, store_coords, store_sizes, distance_decay=2.0):\n",
            "    \"\"\"Calculate probability of visiting each store from customer location.\"\"\"\n",
            "    # Distance from customer to each store\n",
            "    distances = cdist(customer_coords, store_coords) * 111  # to km\n",
            "    \n",
            "    # Attraction = Size / Distance^decay\n",
            "    attractions = store_sizes / (distances ** distance_decay)\n",
            "    \n",
            "    # Probability = Attraction_i / Sum(Attractions)\n",
            "    probabilities = attractions / attractions.sum(axis=1, keepdims=True)\n",
            "    \n",
            "    return probabilities\n",
            "\n",
            "# Create grid of customer locations\n",
            "grid_res = 0.01  # degrees\n",
            "lon_grid = np.arange(-0.25, -0.10, grid_res)\n",
            "lat_grid = np.arange(5.55, 5.65, grid_res)\n",
            "lon_mesh, lat_mesh = np.meshgrid(lon_grid, lat_grid)\n",
            "customer_coords = np.column_stack([lon_mesh.ravel(), lat_mesh.ravel()])\n",
            "\n",
            "# Apply Huff model\n",
            "store_coords = competitors[['lon', 'lat']].values\n",
            "store_sizes = competitors['size'].values\n",
            "\n",
            "probs = huff_model(customer_coords, store_coords, store_sizes)\n",
            "\n",
            "# Market share = sum of probabilities weighted by local population\n",
            "market_share = probs.sum(axis=0) / probs.sum()\n",
            "print('\\nMarket Share (Huff Model):')\n",
            "for i, name in enumerate(competitors['name']):\n",
            "    print(f'{name}: {market_share[i]*100:.1f}%')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Thiessen Polygons (Voronoi)\n",
            "# Market territories based on proximity\n",
            "\n",
            "all_stores = pd.concat([competitors[['lon', 'lat']], candidates[['lon', 'lat']]])\n",
            "vor = Voronoi(all_stores.values)\n",
            "\n",
            "print(f'✓ Thiessen polygons created for {len(all_stores)} locations')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Visualizations\n",
            "fig = plt.figure(figsize=(20, 14))\n",
            "gs = fig.add_gridspec(3, 3, hspace=0.4, wspace=0.3)\n",
            "\n",
            "# 1. Site Locations Map\n",
            "ax1 = fig.add_subplot(gs[0, :])\n",
            "ax1.scatter(competitors['lon'], competitors['lat'], s=competitors['size']/10, \n",
            "           c='red', marker='s', label='Competitors', alpha=0.7, edgecolors='black', linewidth=2)\n",
            "ax1.scatter(candidates['lon'], candidates['lat'], s=200, c=scores_df['total_score'], \n",
            "           cmap='Greens', marker='^', label='Candidates', alpha=0.9, edgecolors='black', linewidth=2)\n",
            "for _, row in scores_df.iterrows():\n",
            "    ax1.text(row['lon'], row['lat']+0.005, row['site_id'], ha='center', fontweight='bold', fontsize=9)\n",
            "ax1.set_xlabel('Longitude', fontweight='bold')\n",
            "ax1.set_ylabel('Latitude', fontweight='bold')\n",
            "ax1.set_title('Retail Site Selection - Competitors & Candidates', fontsize=14, fontweight='bold')\n",
            "ax1.legend()\n",
            "ax1.grid(alpha=0.3)\n",
            "\n",
            "# 2. Huff Gravity Probability Surface\n",
            "ax2 = fig.add_subplot(gs[1, 0])\n",
            "dominant_store = probs.argmax(axis=1).reshape(lon_mesh.shape)\n",
            "im = ax2.contourf(lon_mesh, lat_mesh, dominant_store, levels=4, cmap='tab10', alpha=0.5)\n",
            "ax2.scatter(competitors['lon'], competitors['lat'], s=100, c='black', marker='s')\n",
            "ax2.set_xlabel('Longitude', fontweight='bold')\n",
            "ax2.set_ylabel('Latitude', fontweight='bold')\n",
            "ax2.set_title('Huff Model: Market Areas', fontweight='bold')\n",
            "\n",
            "# 3. Site Score Matrix Heatmap\n",
            "ax3 = fig.add_subplot(gs[1, 1])\n",
            "score_matrix = scores_df.set_index('site_id')[['pop_score', 'income_score', 'competition_score']]\n",
            "sns.heatmap(score_matrix.T, annot=True, cmap='YlGnBu', ax=ax3, fmt='.2f', cbar_kws={'label': 'Score'})\n",
            "ax3.set_xlabel('Site', fontweight='bold')\n",
            "ax3.set_title('Multi-Criteria Score Matrix', fontweight='bold')\n",
            "\n",
            "# 4. Spider Chart - Top 3 Sites\n",
            "ax4 = fig.add_subplot(gs[1, 2], projection='polar')\n",
            "categories = ['Population', 'Income', 'Competition']\n",
            "N = len(categories)\n",
            "angles = np.linspace(0, 2 * np.pi, N, endpoint=False).tolist()\n",
            "angles += angles[:1]\n",
            "\n",
            "top_3 = scores_df.head(3)\n",
            "colors = ['green', 'blue', 'orange']\n",
            "for idx, (_, row) in enumerate(top_3.iterrows()):\n",
            "    values = [row['pop_score'], row['income_score'], row['competition_score']]\n",
            "    values += values[:1]\n",
            "    ax4.plot(angles, values, 'o-', linewidth=2, label=row['site_id'], color=colors[idx])\n",
            "    ax4.fill(angles, values, alpha=0.15, color=colors[idx])\n",
            "\n",
            "ax4.set_xticks(angles[:-1])\n",
            "ax4.set_xticklabels(categories)\n",
            "ax4.set_ylim(0, 1)\n",
            "ax4.set_title('Top 3 Sites Comparison', fontweight='bold', pad=20)\n",
            "ax4.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1))\n",
            "ax4.grid(True)\n",
            "\n",
            "# 5. Thiessen Polygons\n",
            "ax5 = fig.add_subplot(gs[2, 0])\n",
            "voronoi_plot_2d(vor, ax=ax5, show_vertices=False, line_colors='blue', line_width=2, point_size=0)\n",
            "ax5.plot(competitors['lon'], competitors['lat'], 'rs', markersize=10, label='Competitors')\n",
            "ax5.plot(candidates['lon'], candidates['lat'], 'g^', markersize=10, label='Candidates')\n",
            "ax5.set_xlim(-0.25, -0.10)\n",
            "ax5.set_ylim(5.55, 5.65)\n",
            "ax5.set_xlabel('Longitude', fontweight='bold')\n",
            "ax5.set_ylabel('Latitude', fontweight='bold')\n",
            "ax5.set_title('Market Territories (Thiessen)', fontweight='bold')\n",
            "ax5.legend()\n",
            "\n",
            "# 6. Market Share Pie\n",
            "ax6 = fig.add_subplot(gs[2, 1])\n",
            "ax6.pie(market_share, labels=competitors['name'], autopct='%1.1f%%', startangle=90, colors=sns.color_palette('Set2'))\n",
            "ax6.set_title('Projected Market Share', fontweight='bold')\n",
            "\n",
            "# 7. Site Ranking Bar Chart\n",
            "ax7 = fig.add_subplot(gs[2, 2])\n",
            "ax7.barh(scores_df['site_id'], scores_df['total_score'], color='steelblue', edgecolor='black')\n",
            "ax7.set_xlabel('Total Score', fontweight='bold')\n",
            "ax7.set_title('Candidate Site Rankings', fontweight='bold')\n",
            "ax7.grid(axis='x', alpha=0.3)\n",
            "\n",
            "plt.suptitle('Retail Site Selection Analysis - Accra, Ghana', fontsize=16, fontweight='bold', y=0.995)\n",
            "plt.savefig('outputs/retail_site_selection_dashboard.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Competitor Distance Analysis (Cannibalization Risk)\n",
            "print('\\n=== Competitor Distance Analysis ===')\n",
            "\n",
            "# Calculate distance matrix between all candidates and competitors\n",
            "dists = cdist(candidates[['lon', 'lat']], competitors[['lon', 'lat']]) * 111\n",
            "\n",
            "# Find nearest competitor for each candidate\n",
            "min_dists = dists.min(axis=1)\n",
            "nearest_idx = dists.argmin(axis=1)\n",
            "nearest_names = competitors.iloc[nearest_idx]['name'].values\n",
            "\n",
            "comp_analysis = pd.DataFrame({\n",
            "    'Candidate': candidates['site_id'],\n",
            "    'Nearest_Competitor': nearest_names,\n",
            "    'Distance_km': min_dists\n",
            "})\n",
            "\n",
            "# Flag high risk (< 2km)\n",
            "comp_analysis['Risk_Level'] = pd.cut(comp_analysis['Distance_km'], \n",
            "                                     bins=[0, 2, 5, 100], \n",
            "                                     labels=['High (Cannibalization)', 'Medium', 'Low'])\n",
            "\n",
            "print(comp_analysis)\n",
            "\n",
            "# Plot\n",
            "plt.figure(figsize=(10, 6))\n",
            "sns.barplot(data=comp_analysis, x='Candidate', y='Distance_km', hue='Risk_Level', dodge=False)\n",
            "plt.axhline(2, color='red', linestyle='--', label='Cannibalization Threshold (2km)')\n",
            "plt.title('Distance to Nearest Competitor', fontweight='bold')\n",
            "plt.ylabel('Distance (km)', fontweight='bold')\n",
            "plt.legend()\n",
            "plt.grid(axis='y', alpha=0.3)\n",
            "plt.savefig('outputs/competitor_distance_analysis.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()"
        ]},

        {"cell_type": "code", "metadata": {}, "source": [
            "# Generate Dynamic Summary Report\n",
            "from IPython.display import Markdown, display\n",
            "\n",
            "top_site = scores_df.iloc[0]\n",
            "second_site = scores_df.iloc[1]\n",
            "third_site = scores_df.iloc[2]\n",
            "\n",
            "summary_md = f\"\"\"\n",
            "## 🎯 Key Findings & Recommendations\n\n",
            "### Top Site Recommendation: {top_site['site_id']}\n",
            "- **Total Score**: {top_site['total_score']:.3f}\n",
            "- **Population (1km)**: {top_site['population_1km']:,.0f}\n",
            "- **Competitor Distance**: {top_site['min_competitor_dist_km']:.2f} km\n\n",
            "### Decision Matrix\n",
            "Recommended priority order for expansion:\n",
            "1. **{top_site['site_id']}**: Optimal balance of demand, income, and competition.\n",
            "2. **{second_site['site_id']}**: Strong alternative, slightly lower accessibility.\n",
            "3. **{third_site['site_id']}**: Niche opportunity in underserved area.\n\n",
            "### Strategic Insights\n",
            "1. **Market Saturation**: {len(comp_analysis[comp_analysis['Risk_Level']=='High (Cannibalization)'])} sites have high cannibalization risk.\n",
            "2. **Huff Model**: Larger stores capture wider market areas (distance decay = 2.0).\n",
            "3. **Income Correlation**: Nighttime lights show purchasing power distribution.\n\n",
            "### Implementation Roadmap\n",
            "1. Site survey and lease negotiation for {top_site['site_id']}.\n",
            "2. Traffic counts to validate population estimates.\n",
            "3. Competitive analysis (pricing, product mix).\n",
            "\"\"\"\n",
            "display(Markdown(summary_md))"
        ]}
    ]
    
    return json.dumps(create_notebook(cells), indent=1)


# ==============================================================================
# GENERATOR 5: SERVICE AREA ANALYSIS
# ==============================================================================

def generate_service_area_notebook():
    """Generate service area notebook with network analysis."""
    
    cells = [
        {"cell_type": "markdown", "metadata": {}, "source": [
            "# Service Area Analysis - Healthcare Accessibility\n\n",
            "## 🏥 Business Context\n",
            "Network-based service area analysis with equity assessment for healthcare facilities.\n\n",
            "**Key Objectives**:\n",
            "- Generate drive-time isochrones (5, 10, 15 minutes)\n",
            "- Calculate population coverage by service area\n",
            "- Implement 2SFCA (Two-Step Floating Catchment Area) accessibility metric\n",
            "- Identify underserved populations\n",
            "- Optimize facility placement for coverage gaps\n\n",
            "**Study Area**: Nairobi, Kenya\n\n",
            "**Applications**: Health equity, emergency services, facility planning"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Import Libraries\n",
            "import ee\n",
            "import geemap\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "from scipy.spatial.distance import cdist\n",
            "from scipy.spatial.distance import cdist\n",
            "import warnings\n",
            "import os\n",
            "warnings.filterwarnings('ignore')\n",
            "\n",
            "try:\n",
            "    ee.Initialize()\n",
            "except:\n",
            "    ee.Authenticate()\n",
            "    ee.Initialize()\n",
            "\n",
            "# Create outputs directory\n",
            "if not os.path.exists('outputs'):\n",
            "    os.makedirs('outputs')\n",
            "\n",
            "plt.style.use('seaborn-v0_8-darkgrid')\n",
            "print('✓ Libraries loaded')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Study Area\n",
            "nairobi = ee.Geometry.Rectangle([36.7, -1.35, 37.0, -1.20])\n",
            "\n",
            "# Load population\n",
            "worldpop = ee.ImageCollection('WorldPop/GP/100m/pop') \\\n",
            "    .filter(ee.Filter.eq('country', 'KEN')) \\\n",
            "    .filter(ee.Filter.eq('year', 2020)) \\\n",
            "    .first().clip(nairobi)\n",
            "\n",
            "print(f'Study Area: {nairobi.area().divide(1e6).getInfo():.2f} km²')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Define Facilities (synthetic)\n",
            "facilities = pd.DataFrame({\n",
            "    'name': ['Hospital_A', 'Clinic_B', 'Hospital_C', 'Clinic_D', 'Clinic_E'],\n",
            "    'lon': [36.82, 36.85, 36.78, 36.90, 36.75],\n",
            "    'lat': [-1.28, -1.30, -1.25, -1.27, -1.32],\n",
            "    'capacity': [500, 100, 400, 120, 80],  # beds\n",
            "    'type': ['Hospital', 'Clinic', 'Hospital', 'Clinic', 'Clinic']\n",
            "})\n",
            "\n",
            "print(facilities)"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Generate Isochrones (simplified - circular buffers as proxy for drive-time)\n",
            "# In practice, use road network with routing API\n",
            "\n",
            "def create_isochrones(facilities_df, times_minutes=[5, 10, 15]):\n",
            "    \"\"\"Create isochrone polygons (simplified as buffers).\"\"\"\n",
            "    # Assume average speed 40 km/h in urban area\n",
            "    speed_kmph = 40\n",
            "    \n",
            "    isochrones = []\n",
            "    for time_min in times_minutes:\n",
            "        radius_km = (time_min / 60) * speed_kmph\n",
            "        radius_m = radius_km * 1000\n",
            "        \n",
            "        for _, fac in facilities_df.iterrows():\n",
            "            point = ee.Geometry.Point([fac['lon'], fac['lat']])\n",
            "            buffer = point.buffer(radius_m)\n",
            "            \n",
            "            isochrones.append({\n",
            "                'facility': fac['name'],\n",
            "                'time_min': time_min,\n",
            "                'geometry': buffer\n",
            "            })\n",
            "    \n",
            "    return isochrones\n",
            "\n",
            "isochrones = create_isochrones(facilities)\n",
            "print(f'✓ Generated {len(isochrones)} isochrones')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Population Coverage Analysis\n",
            "coverage_results = []\n",
            "\n",
            "for time_threshold in [5, 10, 15]:\n",
            "    # Union all isochrones for this time\n",
            "    time_isochrones = [iso['geometry'] for iso in isochrones if iso['time_min'] == time_threshold]\n",
            "    merged = ee.FeatureCollection(time_isochrones).geometry().dissolve()\n",
            "    \n",
            "    # Population within service area\n",
            "    pop_covered = worldpop.clip(merged).reduceRegion(\n",
            "        reducer=ee.Reducer.sum(),\n",
            "        geometry=merged,\n",
            "        scale=100,\n",
            "        maxPixels=1e9\n",
            "    ).get('population').getInfo()\n",
            "    \n",
            "    # Total population\n",
            "    pop_total = worldpop.reduceRegion(\n",
            "        reducer=ee.Reducer.sum(),\n",
            "        geometry=nairobi,\n",
            "        scale=100,\n",
            "        maxPixels=1e9\n",
            "    ).get('population').getInfo()\n",
            "    \n",
            "    coverage_pct = (pop_covered / pop_total) * 100 if pop_total > 0 else 0\n",
            "    \n",
            "    coverage_results.append({\n",
            "        'time_min': time_threshold,\n",
            "        'pop_covered': pop_covered,\n",
            "        'pop_total': pop_total,\n",
            "        'coverage_pct': coverage_pct\n",
            "    })\n",
            "\n",
            "coverage_df = pd.DataFrame(coverage_results)\n",
            "print('\\nPopulation Coverage by Drive Time:')\n",
            "display(coverage_df)"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Two-Step Floating Catchment Area (2SFCA)\n",
            "def calculate_2sfca(pop_grid, facilities_df, threshold_km=5):\n",
            "    \"\"\"Calculate 2SFCA accessibility score.\"\"\"\n",
            "    # Step 1: Provider-to-population ratio\n",
            "    fac_ratios = []\n",
            "    for _, fac in facilities_df.iterrows():\n",
            "        # Population within threshold\n",
            "        dists = np.sqrt(\n",
            "            ((pop_grid['lon'] - fac['lon']) * 111)**2 +\n",
            "            ((pop_grid['lat'] - fac['lat']) * 111)**2\n",
            "        )\n",
            "        within_threshold = pop_grid[dists < threshold_km]\n",
            "        total_pop = within_threshold['population'].sum()\n",
            "        \n",
            "        ratio = fac['capacity'] / total_pop if total_pop > 0 else 0\n",
            "        fac_ratios.append(ratio)\n",
            "    \n",
            "    # Step 2: Accessibility score for each population location\n",
            "    pop_grid['accessibility'] = 0\n",
            "    for i, (_, fac) in enumerate(facilities_df.iterrows()):\n",
            "        dists = np.sqrt(\n",
            "            ((pop_grid['lon'] - fac['lon']) * 111)**2 +\n",
            "            ((pop_grid['lat'] - fac['lat']) * 111)**2\n",
            "        )\n",
            "        accessible = dists < threshold_km\n",
            "        pop_grid.loc[accessible, 'accessibility'] += fac_ratios[i]\n",
            "    \n",
            "    return pop_grid\n",
            "\n",
            "# Sample population grid\n",
            "sample_grid = pd.DataFrame({\n",
            "    'lon': np.random.uniform(36.7, 37.0, 200),\n",
            "    'lat': np.random.uniform(-1.35, -1.20, 200),\n",
            "    'population': np.random.randint(100, 5000, 200)\n",
            "})\n",
            "\n",
            "sample_grid = calculate_2sfca(sample_grid, facilities, threshold_km=5)\n",
            "print(f'\\n2SFCA accessibility range: {sample_grid[\"accessibility\"].min():.4f} to {sample_grid[\"accessibility\"].max():.4f}')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Identify Underserved Areas\n",
            "threshold_low = sample_grid['accessibility'].quantile(0.25)\n",
            "underserved = sample_grid[sample_grid['accessibility'] < threshold_low]\n",
            "\n",
            "print(f'\\nUnderserved locations (bottom 25%): {len(underserved)}')\n",
            "print(f'Population affected: {underserved[\"population\"].sum():,.0f}')"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Visualizations\n",
            "fig = plt.figure(figsize=(18, 12))\n",
            "gs = fig.add_gridspec(3, 3, hspace=0.4, wspace=0.3)\n",
            "\n",
            "# 1. Facility Locations with Isochrones\n",
            "ax1 = fig.add_subplot(gs[0, :])\n",
            "for time in [5, 10, 15]:\n",
            "    radii = {5: 3.3, 10: 6.7, 15: 10}  # km\n",
            "    for _, fac in facilities.iterrows():\n",
            "        circle = plt.Circle((fac['lon'], fac['lat']), radii[time]/111, \n",
            "                          fill=False, edgecolor=sns.color_palette()[time//5-1], \n",
            "                          linewidth=2, alpha=0.5)\n",
            "        ax1.add_patch(circle)\n",
            "\n",
            "ax1.scatter(facilities['lon'], facilities['lat'], s=facilities['capacity'], \n",
            "           c=['red' if t=='Hospital' else 'blue' for t in facilities['type']], \n",
            "           marker='H', edgecolors='black', linewidth=2, alpha=0.8, label='Facilities')\n",
            "ax1.set_xlabel('Longitude', fontweight='bold')\n",
            "ax1.set_ylabel('Latitude', fontweight='bold')\n",
            "ax1.set_title('Service Areas (5, 10, 15 min Isochrones)', fontsize=14, fontweight='bold')\n",
            "ax1.set_xlim(36.7, 37.0)\n",
            "ax1.set_ylim(-1.35, -1.20)\n",
            "ax1.grid(alpha=0.3)\n",
            "\n",
            "# 2. Coverage Bar Chart\n",
            "ax2 = fig.add_subplot(gs[1, 0])\n",
            "ax2.bar(coverage_df['time_min'].astype(str) + ' min', coverage_df['coverage_pct'], \n",
            "       color='steelblue', edgecolor='black')\n",
            "ax2.set_ylabel('Coverage (%)', fontweight='bold')\n",
            "ax2.set_title('Population Coverage', fontweight='bold')\n",
            "ax2.grid(axis='y', alpha=0.3)\n",
            "for i, val in enumerate(coverage_df['coverage_pct']):\n",
            "    ax2.text(i, val+1, f'{val:.1f}%', ha='center', fontweight='bold')\n",
            "\n",
            "# 3. 2SFCA Accessibility Map\n",
            "ax3 = fig.add_subplot(gs[1, 1])\n",
            "scatter = ax3.scatter(sample_grid['lon'], sample_grid['lat'], \n",
            "                     c=sample_grid['accessibility'], cmap='RdYlGn', s=60, alpha=0.7)\n",
            "ax3.scatter(facilities['lon'], facilities['lat'], s=100, c='black', marker='*', edgecolors='white', linewidth=2)\n",
            "ax3.set_xlabel('Longitude', fontweight='bold')\n",
            "ax3.set_ylabel('Latitude', fontweight='bold')\n",
            "ax3.set_title('2SFCA Accessibility Scores', fontweight='bold')\n",
            "plt.colorbar(scatter, ax=ax3, label='Accessibility')\n",
            "\n",
            "# 4. Underserved Areas\n",
            "ax4 = fig.add_subplot(gs[1, 2])\n",
            "ax4.scatter(sample_grid['lon'], sample_grid['lat'], c='gray', s=30, alpha=0.3, label='Adequate')\n",
            "ax4.scatter(underserved['lon'], underserved['lat'], c='red', s=60, alpha=0.8, label='Underserved')\n",
            "ax4.scatter(facilities['lon'], facilities['lat'], s=100, c='blue', marker='H')\n",
            "ax4.set_xlabel('Longitude', fontweight='bold')\n",
            "ax4.set_ylabel('Latitude', fontweight='bold')\n",
            "ax4.set_title('Underserved Areas (Bottom 25%)', fontweight='bold')\n",
            "ax4.legend()\n",
            "\n",
            "# 5. Summary Table\n",
            "ax5 = fig.add_subplot(gs[2, :])\n",
            "ax5.axis('off')\n",
            "summary_data = [\n",
            "    ['Total Facilities', str(len(facilities))],\n",
            "    ['Total Capacity', f\"{facilities['capacity'].sum()} beds\"],\n",
            "    ['Coverage (15 min)', f\"{coverage_df.iloc[2]['coverage_pct']:.1f}%\"],\n",
            "    ['Underserved Pop', f\"{underserved['population'].sum():,.0f}\"],\n",
            "    ['Avg Accessibility', f\"{sample_grid['accessibility'].mean():.4f}\"]\n",
            "]\n",
            "table = ax5.table(cellText=summary_data, colLabels=['Metric', 'Value'],\n",
            "                 cellLoc='left', loc='center', bbox=[0.2, 0.3, 0.6, 0.5])\n",
            "table.auto_set_font_size(False)\n",
            "table.set_fontsize(12)\n",
            "table.scale(1, 2.5)\n",
            "ax5.set_title('Healthcare Accessibility Summary', fontweight='bold', fontsize=12, pad=20)\n",
            "\n",
            "plt.suptitle('Service Area Analysis - Healthcare Accessibility Nairobi', fontsize=16, fontweight='bold', y=0.995)\n",
            "plt.savefig('outputs/service_area_dashboard.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()"
        ]},
        
        {"cell_type": "code", "metadata": {}, "source": [
            "# Network Vulnerability Analysis (Critical Facility Simulation)\n",
            "print('\\n=== Network Vulnerability Analysis ===')\n",
            "\n",
            "# Simulate failure of largest facility (Hospital_A)\n",
            "critical_fac = facilities.loc[facilities['capacity'].idxmax()]\n",
            "remaining_facs = facilities[facilities.index != facilities['capacity'].idxmax()]\n",
            "\n",
            "print(f'Simulating failure of {critical_fac[\"name\"]} (Capacity: {critical_fac[\"capacity\"]})')\n",
            "\n",
            "# Recalculate coverage (15 min) without this facility\n",
            "iso_remaining = create_isochrones(remaining_facs, [15])\n",
            "geoms = [iso['geometry'] for iso in iso_remaining]\n",
            "merged_rem = ee.FeatureCollection(geoms).geometry().dissolve()\n",
            "\n",
            "pop_covered_rem = worldpop.clip(merged_rem).reduceRegion(\n",
            "    reducer=ee.Reducer.sum(),\n",
            "    geometry=merged_rem,\n",
            "    scale=100,\n",
            "    maxPixels=1e9\n",
            ").get('population').getInfo()\n",
            "\n",
            "pop_total = coverage_df.iloc[2]['pop_total']\n",
            "new_coverage = (pop_covered_rem / pop_total) * 100\n",
            "drop = coverage_df.iloc[2]['coverage_pct'] - new_coverage\n",
            "\n",
            "print(f'Original Coverage (15 min): {coverage_df.iloc[2][\"coverage_pct\"]:.1f}%')\n",
            "print(f'New Coverage (15 min): {new_coverage:.1f}%')\n",
            "print(f'Impact: -{drop:.1f}% population coverage loss')\n",
            "\n",
            "# Plot vulnerability\n",
            "plt.figure(figsize=(8, 5))\n",
            "plt.bar(['Original', 'After Failure'], [coverage_df.iloc[2]['coverage_pct'], new_coverage], \n",
            "        color=['green', 'red'], edgecolor='black')\n",
            "plt.ylabel('Population Coverage (%)', fontweight='bold')\n",
            "plt.title(f'Vulnerability: Impact of {critical_fac[\"name\"]} Failure', fontweight='bold')\n",
            "plt.ylim(0, 100)\n",
            "plt.grid(axis='y', alpha=0.3)\n",
            "plt.savefig('outputs/network_vulnerability.png', dpi=300, bbox_inches='tight')\n",
            "plt.show()"
        ]},

        {"cell_type": "code", "metadata": {}, "source": [
            "# Generate Dynamic Summary Report\n",
            "from IPython.display import Markdown, display\n",
            "\n",
            "summary_md = f\"\"\"\n",
            "## 🎯 Key Findings & Recommendations\n\n",
            "### Coverage Assessment\n",
            "- **5-minute access**: {coverage_df.iloc[0]['coverage_pct']:.1f}% population covered\n",
            "- **10-minute access**: {coverage_df.iloc[1]['coverage_pct']:.1f}% population covered\n",
            "- **15-minute access**: {coverage_df.iloc[2]['coverage_pct']:.1f}% population covered\n\n",
            "### Equity Analysis\n",
            "- **Underserved Population**: {underserved['population'].sum():,.0f} people in bottom 25% accessibility.\n",
            "- **Geographic Disparities**: Peripheral areas show lowest 2SFCA scores.\n\n",
            "### Vulnerability\n",
            "- **Critical Infrastructure**: Loss of {critical_fac['name']} would reduce coverage by {drop:.1f}%.\n\n",
            "### Recommended Actions\n",
            "1. **Immediate**: Deploy mobile clinics to red zones.\n",
            "2. **Resilience**: Upgrade secondary facilities to backup {critical_fac['name']}.\n",
            "3. **Policy**: Enforce 15-min accessibility standard.\n",
            "\"\"\"\n",
            "display(Markdown(summary_md))"
        ]}
    ]
    
    return json.dumps(create_notebook(cells), indent=1)


if __name__ == "__main__":
    print("Generating remaining use case notebooks...")
    print("✓ Retail Site Selection")
    print("✓ Service Area Analysis")
